import type { Question } from '../../game/types'

export const APTITUDE_QUESTIONS: Question[] = [
  {
    id: 'apt-1',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'A shirt costs ₹800. The price rises 25%, then falls 20%. What is the final price?',
    choices: ['₹800', '₹840', '₹780', '₹1000'],
    answer: [0],
    explain:
      '800 × 1.25 = 1000, then 1000 × 0.80 = 800. Back where we started. The trap is assuming +25% then −20% cancel out only by coincidence — they do here because the percentages apply to different bases. General rule: a rise of x% followed by a fall of y% gives a net change of (x − y − xy/100)%. Here: 25 − 20 − 5 = 0.',
    hint: 'The 20% decrease applies to the *new* price, not the original one. Compute in order.',
    followUp: 'What if it rose 20% then fell 25%? Work it out — does order matter?',
    tags: ['percentages'],
  },
  {
    id: 'apt-2',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A can finish a job in 12 days, B in 18 days. Working together, how many days?',
    choices: ['7.2 days', '15 days', '6 days', '30 days'],
    answer: [0],
    explain:
      'Work in rates, never in days. A does 1/12 of the job per day, B does 1/18. Together: 1/12 + 1/18 = 3/36 + 2/36 = 5/36 per day. Time = 36/5 = **7.2 days**. Sanity check that always works: the combined time must be less than the faster worker alone (12), so any answer above 12 is wrong by inspection.',
    hint: 'Convert "days to finish" into "fraction of job per day", then add the rates.',
    followUp: 'If A and B together take 7.2 days and A alone takes 12, how would you find B alone?',
    tags: ['time-work', 'classic'],
  },
  {
    id: 'apt-3',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A train 200m long travelling at 72 km/h crosses a 100m bridge. How long does it take?',
    choices: ['5 seconds', '10 seconds', '15 seconds', '20 seconds'],
    answer: [2],
    explain:
      'Total distance = train length + bridge length = 300m (the train is clear only when its tail leaves the bridge). Convert speed: 72 km/h × 5/18 = 20 m/s. Time = 300/20 = **15 seconds**. The two things people forget: adding the train\'s own length, and the 5/18 conversion factor.',
    hint: 'The train has not finished crossing until its last carriage is off the bridge.',
    tags: ['speed-distance', 'classic'],
  },
  {
    id: 'apt-4',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'The average age of 10 students is 15. A teacher joins and the average becomes 16. How old is the teacher?',
    choices: ['16', '25', '26', '30'],
    answer: [2],
    explain:
      'Total before = 10 × 15 = 150. Total after = 11 × 16 = 176. Teacher = 176 − 150 = **26**. The shortcut worth internalising: the newcomer must be the new average *plus* the total lift they gave everyone else — 16 + (10 × 1) = 26.',
    hint: 'Work with totals rather than averages, then take the difference.',
    tags: ['averages'],
  },
  {
    id: 'apt-5',
    world: 'aptitude',
    skill: 'apt.logical',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What comes next: 2, 6, 12, 20, 30, ___ ?',
    choices: ['36', '40', '42', '44'],
    answer: [2],
    explain:
      'Differences are 4, 6, 8, 10 — increasing by 2 each time, so the next gap is 12: 30 + 12 = **42**. Equivalently the sequence is n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42. When a series looks irregular, always compute the first differences before anything else.',
    hint: 'Write down the gaps between consecutive terms and look at those.',
    tags: ['series'],
  },
  {
    id: 'apt-6',
    world: 'aptitude',
    skill: 'apt.logical',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'All roses are flowers. Some flowers fade quickly. Which conclusion definitely follows?',
    choices: [
      'All roses fade quickly',
      'Some roses fade quickly',
      'Neither conclusion definitely follows',
      'No roses fade quickly',
    ],
    answer: [2],
    explain:
      'Roses are a subset of flowers, but "some flowers fade quickly" does not tell us *which* flowers. The fading ones could all be tulips. Neither conclusion is guaranteed. The discipline for syllogisms: only accept what must be true in *every* possible arrangement — a single counterexample diagram kills a conclusion.',
    hint: 'Try to draw a diagram where the fading flowers and the roses do not overlap at all.',
    tags: ['syllogism', 'classic'],
  },
  {
    id: 'apt-7',
    world: 'aptitude',
    skill: 'apt.logical',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'If CAT is coded as DBU, how is DOG coded?',
    choices: ['EPH', 'DPH', 'EOH', 'FQI'],
    answer: [0],
    explain:
      'Each letter shifts forward by one: C→D, A→B, T→U. Applying the same shift to DOG: D→E, O→P, G→H = **EPH**. For coding-decoding questions, always write the alphabet positions out — the pattern is usually a constant shift, a reversal, or a positional shift that increases across the word.',
    hint: 'Compare each letter of CAT to the matching letter of DBU. What is the constant relationship?',
    tags: ['coding'],
  },
  {
    id: 'apt-8',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'A sum doubles in 5 years at simple interest. In how many years does it triple at the same rate?',
    choices: ['10 years', '15 years', '7.5 years', '20 years'],
    answer: [0],
    explain:
      'Doubling means the interest earned equals the principal, so 5 years produces 100% interest — 20% per year. Tripling requires 200% interest, which at 20% per year takes **10 years**. This only works because simple interest is linear; the compound-interest version of this question has a completely different answer.',
    hint: 'Under simple interest, how much interest was earned in those 5 years relative to the principal?',
    followUp: 'How would your approach change if this were compound interest?',
    tags: ['interest'],
  },
  {
    id: 'apt-9',
    world: 'aptitude',
    skill: 'apt.verbal',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Find the grammatical error: "Each of the candidates were asked to submit their résumé."',
    choices: [
      'No error',
      '"were" should be "was" — "each" is singular',
      '"candidates" should be "candidate"',
      '"submit" should be "submitted"',
    ],
    answer: [1],
    explain:
      '"Each" is always singular, so the verb must be "was" — the plural noun in the intervening prepositional phrase is a distractor. The rule: the verb agrees with the *subject*, never with a noun inside a phrase between subject and verb. Same trap with "neither", "either", "every one of".',
    hint: 'Strip out the phrase "of the candidates" and read the sentence again.',
    tags: ['grammar'],
  },
  {
    id: 'apt-10',
    world: 'aptitude',
    skill: 'apt.data',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A company\'s revenue: 2021 = ₹40cr, 2022 = ₹50cr, 2023 = ₹65cr. Which year had the highest percentage growth?',
    choices: ['2022 (25%)', '2023 (30%)', 'Both equal', 'Cannot be determined'],
    answer: [1],
    explain:
      '2022 growth = (50−40)/40 = 25%. 2023 growth = (65−50)/50 = 30%. So 2023 wins. The trap is comparing absolute increases (10 vs 15) instead of percentages relative to the *previous* year\'s base — DI sets deliberately construct cases where the two rankings disagree.',
    hint: 'Percentage growth is always measured against the previous year\'s value, not a fixed base.',
    tags: ['data-interpretation'],
  },
  {
    id: 'apt-11',
    world: 'aptitude',
    skill: 'apt.quant',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'In how many ways can the letters of the word "LEVEL" be arranged?',
    choices: ['120', '60', '30', '24'],
    answer: [2],
    explain:
      'LEVEL has 5 letters with L repeating twice and E repeating twice. Arrangements = 5! / (2! × 2!) = 120/4 = **30**. Whenever letters repeat, divide by the factorial of each repeat count — otherwise you count identical arrangements as distinct.',
    hint: 'Count how many times each letter appears before reaching for 5!.',
    tags: ['permutations'],
  },
  {
    id: 'apt-12',
    world: 'aptitude',
    skill: 'apt.data',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'A bag has 3 red and 5 blue balls. Two are drawn without replacement. P(both red)?',
    choices: ['3/28', '9/64', '1/4', '3/16'],
    answer: [0],
    explain:
      'P(first red) = 3/8. After removing one red, P(second red) = 2/7. Multiply: 3/8 × 2/7 = 6/56 = **3/28**. "Without replacement" is the whole question — both the numerator and denominator shrink. With replacement it would be 3/8 × 3/8 = 9/64, which is offered as the trap answer.',
    hint: 'After the first ball is drawn and kept out, how many red balls and how many total remain?',
    tags: ['probability'],
  },
  {
    id: 'apt-13',
    world: 'aptitude',
    skill: 'apt.logical',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Five people sit in a row. A is left of B. C is right of B. D is between A and B. Who is leftmost?',
    choices: ['A', 'D', 'B', 'Cannot be determined'],
    answer: [0],
    explain:
      'A is left of B, and D sits between them — giving A, D, B in that order. C is to the right of B. The fifth person, E, is unconstrained and could sit anywhere, but nothing places anyone left of A, and A is explicitly left of the rest of the chain. So **A** is leftmost. For arrangement puzzles, draw the fixed chain first and treat unconstrained people separately.',
    hint: 'Build the chain from the constraints, then check whether the unmentioned person can break it.',
    tags: ['arrangement'],
  },
  {
    id: 'apt-14',
    world: 'aptitude',
    skill: 'apt.verbal',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Choose the word closest in meaning to MITIGATE.',
    choices: ['Intensify', 'Alleviate', 'Postpone', 'Complicate'],
    answer: [1],
    explain:
      'To mitigate is to make less severe — alleviate is the direct synonym. "Intensify" is the antonym, offered as the standard distractor. A useful habit for vocabulary sections: recall the word in a real phrase ("mitigate the damage", "mitigating circumstances") rather than trying to recall a dictionary definition cold.',
    hint: 'Think of the phrase "mitigating circumstances" — do they make a punishment harsher or softer?',
    tags: ['vocabulary'],
  },
]
