import type { Question } from '../../game/types'

/**
 * C++ Arena — aimed at competitive programming.
 *
 * The bias throughout is toward the things that actually decide a contest
 * submission: overflow, complexity, I/O speed, iterator invalidation, and
 * knowing which STL call already solves the sub-problem.
 */
export const CPP_QUESTIONS: Question[] = [
  {
    id: 'cpp-1',
    world: 'cpp',
    skill: 'cpp.basics',
    kind: 'predict-output',
    difficulty: 2,
    prompt: 'What does this print on a typical 64-bit judge?',
    code: 'int a = 100000;\nint b = 100000;\ncout << a * b << endl;',
    choices: ['10000000000', '1410065408', '0', 'Compilation error'],
    answer: [1],
    explain:
      '`int` is 32-bit, so it maxes at 2,147,483,647. 10¹⁰ overflows and wraps to **1410065408**. Both operands are `int`, so the multiplication happens in `int` *before* anything is widened — casting the result afterwards does not help. Fix it at the operand: `(long long)a * b`, or declare them `long long`. This single bug accounts for an enormous share of wrong-answer verdicts.',
    hint: 'What is the largest value a 32-bit signed integer can hold, and what is 100000 × 100000?',
    followUp: 'Why does `long long c = a * b;` still give the wrong answer here?',
    tags: ['overflow', 'classic'],
  },
  {
    id: 'cpp-2',
    world: 'cpp',
    skill: 'cpp.basics',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Your solution reads 10⁶ integers with `cin` and gets TLE. What is the standard first fix?',
    choices: [
      'Switch every `int` to `long long`',
      'Add `ios_base::sync_with_stdio(false); cin.tie(nullptr);`',
      'Read into a `set` instead of a `vector`',
      'Use `endl` instead of `"\\n"`',
    ],
    answer: [1],
    explain:
      'By default C++ streams stay synchronised with C stdio so `cin` and `scanf` can be mixed — that synchronisation is what makes `cin` slow. Disabling it, plus untying `cin` from `cout` (which otherwise flushes before every read), typically gives a 3–5× speedup on large input. Caveat: once you call this, do **not** mix in `scanf`/`printf`.',
    hint: 'The slowness is not the parsing — it is a compatibility guarantee the stream makes by default.',
    followUp: 'Why is `endl` a problem in a tight output loop, and what should you use instead?',
    tags: ['fast-io', 'classic'],
  },
  {
    id: 'cpp-3',
    world: 'cpp',
    skill: 'cpp.basics',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is `-7 / 2` and `-7 % 2` in C++?',
    choices: ['-4 and 1', '-3 and -1', '-3 and 1', '-4 and -1'],
    answer: [1],
    explain:
      'Since C++11, integer division truncates **toward zero**, so `-7 / 2` is `-3` (not `-4`). The remainder then follows the identity `(a/b)*b + a%b == a`, giving `-7 % 2 == -1`. This bites constantly in modular arithmetic: `(-3) % MOD` is negative, so the safe idiom is `((x % MOD) + MOD) % MOD`.',
    hint: 'C++ truncates toward zero, unlike Python which floors toward negative infinity.',
    followUp: 'How do you write a modulo that always returns a non-negative result?',
    tags: ['integers', 'gotcha'],
  },
  {
    id: 'cpp-4',
    world: 'cpp',
    skill: 'cpp.basics',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'A judge allows 1 second. Roughly how many simple operations can you assume fit?',
    choices: ['About 10⁵', 'About 10⁸', 'About 10¹²', 'It cannot be estimated'],
    answer: [1],
    explain:
      'The working rule is ~10⁸ simple operations per second in C++. That is what lets you pick an algorithm from the constraints before writing any code: n ≤ 10⁵ rules out O(n²) (10¹⁰) and points at O(n log n); n ≤ 5000 permits O(n²); n ≤ 20 invites bitmask DP at O(2ⁿ·n). Constant factors matter too — heavy `map` or `set` use can cost 5–10× a plain array.',
    hint: 'Read the constraint, then work backwards to the complexity that fits inside one second.',
    followUp: 'Given n ≤ 200000, which complexities are safe and which are not?',
    tags: ['complexity', 'classic'],
  },
  {
    id: 'cpp-5',
    world: 'cpp',
    skill: 'cpp.stl',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the complexity of lookup in `std::map` versus `std::unordered_map`?',
    choices: [
      'Both O(1)',
      'map is O(log n); unordered_map is O(1) average, O(n) worst case',
      'map is O(1); unordered_map is O(log n)',
      'Both O(log n)',
    ],
    answer: [1],
    explain:
      '`map` is a balanced BST — O(log n), keys kept sorted, and it supports `lower_bound`. `unordered_map` is a hash table — O(1) average but O(n) if keys collide. On Codeforces this matters: anti-hash tests deliberately collide the default `unordered_map` hash and blow it up to O(n²). Either use a custom hash with a random seed, or just use `map` and accept the log.',
    hint: 'One keeps its keys in sorted order; that ordering is not free.',
    followUp: 'When would you specifically need `map` even though `unordered_map` is faster?',
    tags: ['stl', 'complexity', 'classic'],
  },
  {
    id: 'cpp-6',
    world: 'cpp',
    skill: 'cpp.stl',
    kind: 'mcq',
    difficulty: 3,
    prompt: '`std::priority_queue<int> pq;` — what does `pq.top()` return?',
    choices: [
      'The smallest element',
      'The largest element',
      'The most recently pushed element',
      'Undefined until you sort it',
    ],
    answer: [1],
    explain:
      'The default is a **max-heap**, so `top()` is the largest. For a min-heap — which is what Dijkstra and most k-smallest problems need — declare `priority_queue<int, vector<int>, greater<int>> pq;`. A common shortcut for ints is to push negated values into the default max-heap and negate on the way out.',
    hint: 'The default comparator is `less<T>`, and the heap keeps the "greatest" element per that comparator on top.',
    followUp: 'Write the declaration for a min-heap of `pair<int,int>`.',
    tags: ['stl', 'heap', 'classic'],
  },
  {
    id: 'cpp-7',
    world: 'cpp',
    skill: 'cpp.stl',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What is the complexity of `vector::push_back` when the vector is full?',
    choices: [
      'O(1) always',
      'O(n) for that one call, but O(1) amortised across many pushes',
      'O(log n)',
      'O(n) for every push',
    ],
    answer: [1],
    explain:
      'When capacity runs out the vector allocates a larger buffer (typically 2×) and copies everything — O(n) for that call. Because the capacity doubles, those reallocations get exponentially rarer, so the cost averaged over n pushes is O(1) amortised. If you know the size up front, `reserve(n)` avoids the copies entirely and is a free constant-factor win.',
    hint: 'Look at how often a reallocation actually happens as the vector grows.',
    tags: ['stl', 'complexity'],
  },
  {
    id: 'cpp-8',
    world: 'cpp',
    skill: 'cpp.stl',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'How do you declare an n×m 2D array of ints initialised to 0?',
    choices: [
      'vector<vector<int>> g(n, m);',
      'vector<vector<int>> g(n, vector<int>(m, 0));',
      'vector<int> g[n][m];',
      'vector<vector<int>> g{n, m, 0};',
    ],
    answer: [1],
    explain:
      'The outer vector holds n copies of an inner `vector<int>` of length m filled with 0. `vector<vector<int>> g(n, m)` does not compile — the second argument must be the element to copy, not a size. Note that a `vector<vector<int>>` scatters rows across the heap; for very hot inner loops a single flat `vector<int>` of size n*m indexed as `g[i*m+j]` is measurably faster.',
    hint: 'The second constructor argument is the *value* each of the n slots is filled with.',
    tags: ['stl'],
  },
  {
    id: 'cpp-9',
    world: 'cpp',
    skill: 'cpp.algos',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'On a sorted vector, what is the difference between `lower_bound` and `upper_bound`?',
    choices: [
      'lower_bound finds the minimum, upper_bound the maximum',
      'lower_bound gives the first element >= x; upper_bound gives the first element > x',
      'lower_bound searches left-to-right, upper_bound right-to-left',
      'They are identical for sorted input',
    ],
    answer: [1],
    explain:
      '`lower_bound` returns an iterator to the first element **not less than** x; `upper_bound` returns the first element **strictly greater** than x. So the count of elements equal to x is `upper_bound(x) - lower_bound(x)`. Both are O(log n) on random-access iterators — but on a `std::set` you must call the *member* `s.lower_bound(x)`, because the free function degrades to O(n) on a non-random-access iterator.',
    hint: 'One of them includes an exact match, the other steps past it.',
    followUp: 'How would you count occurrences of x in a sorted vector in O(log n)?',
    tags: ['stl', 'binary-search', 'classic'],
  },
  {
    id: 'cpp-10',
    world: 'cpp',
    skill: 'cpp.algos',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'How do you sort a `vector<int> v` in descending order?',
    choices: [
      'sort(v.rbegin(), v.rend());',
      'sort(v.begin(), v.end(), greater<int>());',
      'Both of the above work',
      'reverse(v.begin(), v.end()); only',
    ],
    answer: [2],
    explain:
      'Both are idiomatic and both are O(n log n). `sort(v.rbegin(), v.rend())` sorts through reverse iterators; `sort(v.begin(), v.end(), greater<int>())` passes an explicit comparator. For custom types, pass a lambda: `sort(v.begin(), v.end(), [](auto& a, auto& b){ return a.second > b.second; })`. The comparator must be a strict weak ordering — returning `<=` instead of `<` is undefined behaviour and really does crash.',
    hint: 'There is more than one correct way here.',
    followUp: 'Why does a comparator that returns `a <= b` cause a runtime crash rather than just a wrong order?',
    tags: ['stl', 'sorting'],
  },
  {
    id: 'cpp-11',
    world: 'cpp',
    skill: 'cpp.algos',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What does `next_permutation(v.begin(), v.end())` do and what must you do first?',
    choices: [
      'Generates a random permutation; no precondition',
      'Rearranges into the next lexicographically greater permutation and returns false when it wraps — sort ascending first to enumerate all of them',
      'Returns the number of permutations',
      'Reverses the vector',
    ],
    answer: [1],
    explain:
      'It transforms the range into the next lexicographically greater permutation in O(n), returning `false` (and resetting to sorted order) once it wraps past the last one. To enumerate every permutation, sort ascending first, then `do { ... } while (next_permutation(...));`. Useful for brute force at n ≤ 10 or so — 10! is about 3.6 million, which fits; 12! does not.',
    hint: 'It gives you the *next* one in order, which only enumerates everything if you start from the first.',
    tags: ['stl', 'brute-force'],
  },
  {
    id: 'cpp-12',
    world: 'cpp',
    skill: 'cpp.memory',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Your recursive DFS takes `vector<int> adj[]` by value and TLEs. Why?',
    choices: [
      'Recursion is always slower than iteration',
      'Passing by value deep-copies the whole structure on every call',
      'Vectors cannot be used in recursion',
      'The stack overflows',
    ],
    answer: [1],
    explain:
      'A by-value parameter copies the entire container on every single call — turning an O(V+E) traversal into something far worse. Pass by `const&` when you only read, or `&` when you mutate. This is the single most common accidental-TLE in C++ contest code, and it is invisible in the algorithm itself: the complexity you reasoned about is right, the parameter list is what betrays you.',
    hint: 'Look at what happens to the container at the moment the function is entered.',
    followUp: 'When is passing by value actually the right choice?',
    tags: ['performance', 'classic'],
  },
  {
    id: 'cpp-13',
    world: 'cpp',
    skill: 'cpp.memory',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What is wrong here?',
    code: 'vector<int> v = {1, 2, 3};\nint& first = v[0];\nv.push_back(4);\ncout << first;',
    choices: [
      'Nothing — it prints 1',
      'push_back may reallocate, leaving `first` dangling — undefined behaviour',
      'It always prints 4',
      'It fails to compile',
    ],
    answer: [1],
    explain:
      'If `push_back` exceeds capacity the vector moves its buffer to new memory and frees the old one — every existing pointer, reference and iterator into it is invalidated. Reading `first` afterwards is undefined behaviour: it may print 1, may print garbage, may crash, and will often behave differently under the judge than on your machine. The same trap applies to iterators in a loop that inserts.',
    hint: 'Where does the vector\'s data physically live, and what happens to it when the vector needs more room?',
    followUp: 'Which containers do *not* invalidate references on insertion, and why?',
    tags: ['iterator-invalidation', 'undefined-behaviour', 'classic'],
  },
  {
    id: 'cpp-14',
    world: 'cpp',
    skill: 'cpp.memory',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the practical difference between a reference and a pointer?',
    choices: [
      'They are identical in every way',
      'A reference must be bound at declaration and cannot be reseated or null; a pointer can be null and reassigned',
      'References are slower',
      'Pointers cannot be passed to functions',
    ],
    answer: [1],
    explain:
      'A reference is an alias — it must be initialised when declared, can never be rebound, and cannot legally be null. A pointer is a variable holding an address: it may be null, may be reassigned, and needs explicit dereferencing. In contest code prefer references for parameters (`const vector<int>&`) since they carry no null case to handle; reach for pointers when you genuinely need optional or rebindable indirection, such as tree or linked-list nodes.',
    hint: 'Think about which one you can point somewhere else after you have created it.',
    tags: ['references'],
  },
  {
    id: 'cpp-15',
    world: 'cpp',
    skill: 'cpp.modern',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the difference between `for (auto x : v)` and `for (auto& x : v)`?',
    choices: [
      'No difference',
      'The first copies each element; the second binds a reference, so it avoids copies and can modify the vector',
      'The second is not valid C++',
      'The first is faster',
    ],
    answer: [1],
    explain:
      '`auto x` copies every element — cheap for `int`, expensive for `string` or `vector`, and writes to `x` are discarded. `auto& x` binds a reference: no copy, and mutations stick. The default habit for reading should be `const auto&`, which avoids the copy and documents that you are not modifying. On a `vector<string>` in a hot loop this alone can be the difference between passing and TLE.',
    hint: 'One of them hands you the element itself; the other hands you a photocopy.',
    tags: ['modern-cpp', 'performance'],
  },
  {
    id: 'cpp-16',
    world: 'cpp',
    skill: 'cpp.modern',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'In a lambda, what is the difference between `[=]` and `[&]`?',
    choices: [
      '`[=]` captures by value (a snapshot); `[&]` captures by reference (live, and dangling if the lambda outlives the scope)',
      '`[=]` is for ints, `[&]` is for objects',
      'They are interchangeable',
      '`[&]` copies, `[=]` references',
    ],
    answer: [0],
    explain:
      '`[=]` copies the captured variables at the point the lambda is created — a snapshot, safe to store and call later. `[&]` captures by reference, so the lambda sees live values but holds dangling references the moment those variables go out of scope. In contest code `[&]` is the common default because lambdas are used immediately (comparators, recursive DFS via `function<void(int)>`), and it avoids copying big captured containers.',
    hint: 'One takes a snapshot at creation time; the other keeps looking at the original.',
    followUp: 'How do you write a recursive lambda in C++?',
    tags: ['lambda', 'modern-cpp'],
  },
  {
    id: 'cpp-17',
    world: 'cpp',
    skill: 'cpp.cp',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Why compute `(a * b) % MOD` as `(1LL * a * b) % MOD` when a and b are ints below MOD ≈ 10⁹?',
    choices: [
      'It is a style convention with no effect',
      'a * b can reach ~10¹⁸, which overflows 32-bit int — the 1LL forces 64-bit multiplication',
      'The modulo operator requires long long',
      'It makes the code faster',
    ],
    answer: [1],
    explain:
      'Two values just under 10⁹ multiply to just under 10¹⁸ — far beyond `int`\'s 2.1×10⁹ limit, so the overflow happens *before* the modulo ever runs. `1LL *` promotes the expression to `long long` (max ~9.2×10¹⁸), which comfortably holds the product. This is the standard idiom in every modular-arithmetic solution and its absence is a silent wrong answer, not a crash.',
    hint: 'Work out the largest possible value of a*b before the % is applied.',
    followUp: 'What if MOD were around 10¹⁸ — would long long still be enough?',
    tags: ['modular', 'overflow', 'classic'],
  },
  {
    id: 'cpp-18',
    world: 'cpp',
    skill: 'cpp.cp',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'You must answer many queries for the sum of a[l..r] on a static array. Best approach?',
    choices: [
      'Loop from l to r for each query — O(n) per query',
      'Precompute prefix sums once in O(n), then answer each query in O(1) as pre[r+1] - pre[l]',
      'Sort the array first',
      'Use a hash map of every possible range',
    ],
    answer: [1],
    explain:
      'Build `pre[i+1] = pre[i] + a[i]` in one O(n) pass, then any range sum is a single subtraction — O(1) per query. With q queries that is O(n + q) instead of O(n·q). Use `long long` for the prefix array, since sums overflow `int` long before the individual values do. If the array also needs *updates*, prefix sums no longer work and you move to a Fenwick tree or segment tree at O(log n) per operation.',
    hint: 'Precompute something once so each query becomes arithmetic rather than a loop.',
    followUp: 'What changes if the array can be updated between queries?',
    tags: ['prefix-sums', 'classic'],
  },
  {
    id: 'cpp-19',
    world: 'cpp',
    skill: 'cpp.cp',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'How do you iterate over every subset of an n-element set using bitmasks?',
    choices: [
      'for (int m = 0; m < n; m++)',
      'for (int m = 0; m < (1 << n); m++) — each m is a subset, bit i set means element i is included',
      'for (int m = 1; m <= n * n; m++)',
      'Bitmasks cannot represent subsets',
    ],
    answer: [1],
    explain:
      'There are 2ⁿ subsets, and each integer from 0 to 2ⁿ−1 encodes one: bit i set means element i is in the subset. Test membership with `m & (1 << i)`, and count set bits with `__builtin_popcount(m)`. Practical limits: n ≤ 20 gives about a million subsets (fine), n ≤ 25 is roughly 3×10⁷ (borderline). Use `1LL << n` once n exceeds 30, or the shift itself overflows.',
    hint: 'How many subsets does an n-element set have, and what range of integers has exactly that many values?',
    followUp: 'How would you enumerate only the submasks of a given mask?',
    tags: ['bitmask', 'classic'],
  },
  {
    id: 'cpp-20',
    world: 'cpp',
    skill: 'cpp.cp',
    kind: 'multi',
    difficulty: 4,
    prompt: 'Constraints say n ≤ 2×10⁵. Which complexities are safe within a 1-second limit? (Select all)',
    choices: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n √n)'],
    answer: [1, 2, 3],
    explain:
      'With n = 2×10⁵: O(n) is 2×10⁵ and O(n log n) about 3.5×10⁶ — both trivially fine. O(n√n) is roughly 9×10⁷, which fits if the constant factor is small (this is why Mo\'s algorithm is viable). O(n²) is 4×10¹⁰ — hundreds of times over budget. Reading n ≤ 2×10⁵ should immediately tell you the intended solution is sorting, a sweep, binary search, or a segment tree — never a nested loop over pairs.',
    hint: 'Compute each one for n = 200000 and compare against roughly 10⁸ operations per second.',
    followUp: 'What does a constraint of n ≤ 20 usually signal about the intended solution?',
    tags: ['complexity', 'classic'],
  },
]
