import type { Question } from '../../game/types'

export const DSA_QUESTIONS: Question[] = [
  {
    id: 'dsa-1',
    world: 'dsa',
    skill: 'dsa.complexity',
    kind: 'mcq',
    difficulty: 1,
    prompt: 'What is the time complexity of this loop?',
    code: 'for i in range(n):\n    for j in range(n):\n        total += grid[i][j]',
    choices: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'],
    answer: [2],
    explain:
      'The inner loop runs n times for each of the n outer iterations, so the body executes n × n times. Nested independent loops multiply; sequential loops add.',
    hint: 'How many times does the innermost statement execute in total?',
    tags: ['big-o'],
  },
  {
    id: 'dsa-2',
    world: 'dsa',
    skill: 'dsa.complexity',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the time complexity?',
    code: 'i = n\nwhile i > 1:\n    i = i // 2\n    work()',
    choices: ['O(n)', 'O(log n)', 'O(n log n)', 'O(√n)'],
    answer: [1],
    explain:
      'Each iteration halves `i`, so the number of iterations is the number of times you can halve n before reaching 1 — that is log₂n. Any time a loop multiplies or divides the counter by a constant factor instead of adding to it, you are in logarithmic territory.',
    hint: 'The counter is not decreasing by 1 each time. How many halvings does it take to get from n to 1?',
    followUp: 'What if the loop body itself were O(n) instead of O(1)?',
    tags: ['big-o'],
  },
  {
    id: 'dsa-3',
    world: 'dsa',
    skill: 'dsa.complexity',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'An algorithm runs in O(n) time and O(n) space. You reduce space to O(1) but the running time doubles. Has the time complexity changed?',
    choices: [
      'Yes, it is now O(2n)',
      'No, it is still O(n) — constant factors are not part of asymptotic complexity',
      'Yes, it is now O(n log n)',
      'It becomes O(1) because space is O(1)',
    ],
    answer: [1],
    explain:
      'Big-O describes growth rate, discarding constant factors and lower-order terms. O(2n) *is* O(n). That said — interviewers do care about the constant in practice, so say "same complexity, roughly 2x the constant factor" rather than pretending it is free.',
    hint: 'Does Big-O notation keep constant multipliers?',
    tags: ['big-o'],
  },
  {
    id: 'dsa-4',
    world: 'dsa',
    skill: 'dsa.arrays',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Given a **sorted** array, find two numbers that sum to a target. What is the optimal approach?',
    choices: [
      'Nested loops over every pair — O(n²)',
      'Two pointers from both ends, moving inward — O(n) time, O(1) space',
      'Sort it again then binary search — O(n log n)',
      'Build a hash set of complements — O(n) time, O(n) space',
    ],
    answer: [1],
    explain:
      'Because the array is sorted you can start with pointers at both ends. If the sum is too large, move the right pointer left; too small, move the left pointer right. Each step eliminates one candidate, so it is O(n) time and O(1) extra space. The hash-set approach is also O(n) time but wastes O(n) space — on an already-sorted input, two pointers strictly dominates.',
    hint: 'The array being sorted is the gift here. What can you conclude when the current pair sums too high?',
    followUp: 'Now the array is *not* sorted. Which approach wins, and why is sorting first usually the wrong call?',
    tags: ['two-pointers', 'classic'],
  },
  {
    id: 'dsa-5',
    world: 'dsa',
    skill: 'dsa.arrays',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Find the maximum sum of any contiguous subarray (Kadane\'s algorithm). What is the core insight?',
    choices: [
      'Sort the array and take the largest k elements',
      'At each index, either extend the previous subarray or start fresh — whichever is larger',
      'Use a sliding window of fixed size k',
      'Compute all prefix sums and take the maximum',
    ],
    answer: [1],
    explain:
      'Kadane keeps one running value: `current = max(x, current + x)`. If the running sum has gone negative it can only hurt, so you discard it and restart at the current element. Track the best value seen along the way. O(n) time, O(1) space. Sliding window does not apply because the subarray length is not fixed.',
    hint: 'If everything you have accumulated so far sums to a negative number, is it ever worth carrying forward?',
    followUp: 'How would you also return the start and end indices of that subarray?',
    tags: ['kadane', 'classic'],
  },
  {
    id: 'dsa-6',
    world: 'dsa',
    skill: 'dsa.hashing',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Average-case time to look up a key in a well-implemented hash table?',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: [0],
    explain:
      'Hashing the key gives you the bucket directly, so the average case is O(1). Worst case degrades to O(n) if every key collides into one bucket — which is why adversarial inputs and poor hash functions matter, and why some languages randomise their hash seed.',
    hint: 'The whole point of hashing is skipping the search.',
    followUp: 'What causes the worst case, and how do real implementations defend against it?',
    tags: ['hashing'],
  },
  {
    id: 'dsa-7',
    world: 'dsa',
    skill: 'dsa.hashing',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Detect whether an array contains any duplicate, in one pass. Best approach?',
    choices: [
      'Compare every pair — O(n²)',
      'Sort then scan neighbours — O(n log n)',
      'Insert into a hash set and return early on the first repeat — O(n)',
      'It cannot be done in one pass',
    ],
    answer: [2],
    explain:
      'Walk the array once, adding each element to a set. If an element is already present you have your duplicate and can return immediately. O(n) time, O(n) space. Sorting is a valid O(n log n) fallback and is the right answer if the interviewer says you cannot use extra space.',
    hint: 'You want to answer "have I seen this before?" in constant time.',
    followUp: 'What if you are told to use O(1) extra space? What is the best you can do then?',
    tags: ['hashing', 'classic'],
  },
  {
    id: 'dsa-8',
    world: 'dsa',
    skill: 'dsa.linked',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'How do you detect a cycle in a singly linked list using O(1) extra space?',
    choices: [
      'Store every visited node in a hash set',
      "Floyd's tortoise and hare — one pointer moves 1 step, the other 2",
      'Reverse the list and compare',
      'Count nodes and compare against the length field',
    ],
    answer: [1],
    explain:
      "Floyd's cycle detection: slow moves one node per step, fast moves two. If there is a cycle the fast pointer laps the slow one and they meet; if fast reaches null there is no cycle. O(n) time, O(1) space. The hash-set version also works but costs O(n) space, which is exactly what the constraint forbids.",
    hint: 'Two runners on a circular track at different speeds will eventually meet.',
    followUp: 'Once they meet, how do you find the node where the cycle actually begins?',
    tags: ['linked-list', 'classic'],
  },
  {
    id: 'dsa-9',
    world: 'dsa',
    skill: 'dsa.linked',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Which data structure naturally checks balanced brackets in an expression?',
    choices: ['Queue', 'Stack', 'Heap', 'Hash map'],
    answer: [1],
    explain:
      'Brackets are last-opened-first-closed, which is exactly LIFO. Push every opening bracket; on a closing bracket, pop and check it matches. The string is balanced if you never mismatch and the stack is empty at the end. A queue (FIFO) would give you the wrong pairing order entirely.',
    hint: 'Which bracket must close first — the most recently opened, or the oldest?',
    tags: ['stack', 'classic'],
  },
  {
    id: 'dsa-10',
    world: 'dsa',
    skill: 'dsa.trees',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Which traversal of a **binary search tree** visits values in sorted ascending order?',
    choices: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
    answer: [1],
    explain:
      'In-order is left → node → right. Since a BST puts everything smaller on the left and everything larger on the right, this visits keys in ascending order. That property is the basis of a whole family of interview questions: validating a BST, finding the kth smallest element, converting a BST to a sorted list.',
    hint: 'Which order visits the entire left subtree before the node itself?',
    followUp: 'Using that fact, how would you validate that a tree really is a BST in O(n)?',
    tags: ['trees', 'bst'],
  },
  {
    id: 'dsa-11',
    world: 'dsa',
    skill: 'dsa.trees',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'You need the k largest elements from a stream of n numbers, where n is huge. Best structure?',
    choices: [
      'Sort everything and slice — O(n log n)',
      'A min-heap of size k — O(n log k) time, O(k) space',
      'A max-heap of size n',
      'A balanced BST holding all n elements',
    ],
    answer: [1],
    explain:
      'Keep a min-heap capped at size k. For each new number, if the heap has fewer than k elements push it; otherwise compare against the root (the smallest of your current top-k) and replace if the new number is larger. O(n log k) time and — crucially for a stream — only O(k) memory. Sorting requires holding all n elements, which you may not be able to do.',
    hint: 'To keep the top k, you need fast access to the *weakest* member currently in your set.',
    followUp: 'Why a min-heap and not a max-heap, when the question asks for the largest elements?',
    tags: ['heap', 'classic'],
  },
  {
    id: 'dsa-12',
    world: 'dsa',
    skill: 'dsa.graphs',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Shortest path in an **unweighted** graph — which algorithm?',
    choices: ['DFS', 'BFS', "Dijkstra's", 'Bellman-Ford'],
    answer: [1],
    explain:
      'BFS explores level by level, so the first time it reaches a node it has done so in the fewest possible edges. That is the shortest path when every edge costs the same. Dijkstra generalises this to weighted edges (and is essentially BFS with a priority queue); DFS gives you *a* path, not the shortest one.',
    hint: 'Which traversal guarantees you reach all distance-1 nodes before any distance-2 node?',
    followUp: 'At what point does BFS stop being correct, and what do you reach for instead?',
    tags: ['graphs', 'bfs'],
  },
  {
    id: 'dsa-13',
    world: 'dsa',
    skill: 'dsa.graphs',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Course scheduling: tasks with prerequisites, find a valid order. What is this problem?',
    choices: [
      'Minimum spanning tree',
      'Topological sort of a directed acyclic graph',
      'Maximum flow',
      'Graph colouring',
    ],
    answer: [1],
    explain:
      'Model each course as a node and each prerequisite as a directed edge. A valid ordering is exactly a topological sort. Two standard implementations: Kahn\'s algorithm (repeatedly take nodes with in-degree 0) or DFS with a post-order reversal. If no valid order exists, the graph has a cycle — which is also how you answer "can all courses be finished?"',
    hint: 'You need an ordering that respects every "must come before" constraint.',
    followUp: 'How does your algorithm detect that the prerequisites are impossible to satisfy?',
    tags: ['graphs', 'toposort', 'classic'],
  },
  {
    id: 'dsa-14',
    world: 'dsa',
    skill: 'dsa.dp',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Which two properties must a problem have for dynamic programming to apply?',
    choices: [
      'Sorted input and unique elements',
      'Optimal substructure and overlapping subproblems',
      'A greedy choice and a spanning tree',
      'Constant space and linear time',
    ],
    answer: [1],
    explain:
      '**Optimal substructure**: the optimal answer is built from optimal answers to smaller instances. **Overlapping subproblems**: the same smaller instances recur many times, so caching pays off. Without overlap, plain divide-and-conquer (like merge sort) is enough — memoising nothing. Without optimal substructure, DP gives wrong answers.',
    hint: 'One property is about how the answer is composed; the other is about why caching helps.',
    followUp: 'Fibonacci has both. Name a problem with optimal substructure but no overlap.',
    tags: ['dp'],
  },
  {
    id: 'dsa-15',
    world: 'dsa',
    skill: 'dsa.dp',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Naive recursive Fibonacci is O(2ⁿ). Memoising it brings it to?',
    choices: ['O(n)', 'O(n log n)', 'O(n²)', 'Still O(2ⁿ)'],
    answer: [0],
    explain:
      'With memoisation each value fib(0)…fib(n) is computed exactly once and reused thereafter — n subproblems, O(1) work each, so O(n) time and O(n) space. Bottom-up tabulation gets the same time and, if you keep only the last two values, O(1) space. That last optimisation is a very common follow-up.',
    hint: 'Count the number of *distinct* subproblems, not the number of recursive calls.',
    followUp: 'Can you get the space down to O(1)? Show me how.',
    tags: ['dp', 'classic'],
  },
  {
    id: 'dsa-16',
    world: 'dsa',
    skill: 'dsa.arrays',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Binary search requires which precondition?',
    choices: [
      'The array contains no duplicates',
      'The array is sorted',
      'The array length is a power of two',
      'The array contains only integers',
    ],
    answer: [1],
    explain:
      'Sortedness is the only requirement — it is what lets you discard half the search space each step. Duplicates are fine (you just may not land on the specific occurrence you wanted, which is why lower-bound/upper-bound variants exist). Watch the classic bug: compute the midpoint as `lo + (hi - lo) // 2` to avoid integer overflow in languages with fixed-width ints.',
    hint: 'What lets you confidently throw away half the array after one comparison?',
    followUp: 'Write the loop invariant for your binary search. Where do off-by-one errors usually creep in?',
    tags: ['binary-search', 'classic'],
  },
  {
    id: 'dsa-17',
    world: 'dsa',
    skill: 'dsa.trees',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the height of a balanced binary tree with n nodes, and why does it matter?',
    choices: [
      'O(n) — it determines memory usage',
      'O(log n) — it bounds search, insert and delete time',
      'O(√n) — it bounds the branching factor',
      'O(1) — height is independent of node count',
    ],
    answer: [1],
    explain:
      'A balanced binary tree roughly doubles its node count with each level, so height is O(log n). Since BST operations walk a single root-to-leaf path, they are O(height). This is exactly why self-balancing trees (AVL, red-black) exist — an unbalanced BST degenerates to a linked list with O(n) operations.',
    hint: 'How many levels do you need to hold n nodes if each level roughly doubles?',
    followUp: 'What input sequence turns an ordinary BST into a linked list?',
    tags: ['trees'],
  },
  {
    id: 'dsa-18',
    world: 'dsa',
    skill: 'dsa.complexity',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Rank these from fastest-growing to slowest-growing.',
    choices: [
      'O(n²) > O(n log n) > O(n) > O(log n)',
      'O(log n) > O(n) > O(n log n) > O(n²)',
      'O(n log n) > O(n²) > O(n) > O(log n)',
      'O(n) > O(n²) > O(log n) > O(n log n)',
    ],
    answer: [0],
    explain:
      'The standard ladder, worst to best: O(2ⁿ) > O(n³) > O(n²) > O(n log n) > O(n) > O(log n) > O(1). Knowing this cold lets you instantly judge whether a proposed solution is an improvement — which is half of what an interviewer is testing when they ask "can you do better?"',
    hint: 'Which grows faster as n gets large: squaring n, or multiplying n by its logarithm?',
    tags: ['big-o'],
  },
]
