import type { Question } from '../../game/types'

/**
 * HR questions are judgement calls rather than facts — the "correct" answer is
 * the one a strong candidate would give, and the explanation teaches the
 * underlying principle rather than a rule.
 */
export const HR_QUESTIONS: Question[] = [
  {
    id: 'hr-1',
    world: 'hr',
    skill: 'hr.story',
    kind: 'mcq',
    difficulty: 2,
    prompt: '"Tell me about yourself." What is the strongest structure for a fresher?',
    choices: [
      'Your full life story from school onwards, chronologically',
      'Present (what you study / build) → strongest relevant project or experience → why this role, in about 90 seconds',
      'A recital of every technology on your résumé',
      'Your hobbies and family background first, to build rapport',
    ],
    answer: [1],
    explain:
      'This is not an icebreaker — it is your one chance to frame the entire interview. Present → relevant proof → why this role gives the interviewer a hook to dig into work you *want* to discuss. Keep it near 90 seconds; going past two minutes reads as an inability to prioritise, which is itself a signal.',
    hint: 'The interviewer is deciding what to ask you next. What would you like that to be?',
    followUp: 'Give me your 90-second version right now. Which project did you lead with, and why that one?',
    tags: ['intro', 'classic'],
  },
  {
    id: 'hr-2',
    world: 'hr',
    skill: 'hr.behaviour',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What does the STAR method stand for?',
    choices: [
      'Skill, Talent, Ambition, Result',
      'Situation, Task, Action, Result',
      'Strategy, Timeline, Approach, Review',
      'Start, Test, Analyse, Report',
    ],
    answer: [1],
    explain:
      '**Situation** (context, briefly), **Task** (what you were responsible for), **Action** (what *you* specifically did), **Result** (the measurable outcome). Two failure modes to avoid: spending 80% of your time on Situation, and saying "we" throughout Action — the interviewer is evaluating you, not your team. Always land the Result with a number where you can.',
    hint: 'Four steps, ending with the outcome.',
    followUp: 'Use STAR to tell me about a time you disagreed with a teammate.',
    tags: ['star', 'classic'],
  },
  {
    id: 'hr-3',
    world: 'hr',
    skill: 'hr.behaviour',
    kind: 'mcq',
    difficulty: 3,
    prompt: '"What is your greatest weakness?" — which approach is strongest?',
    choices: [
      '"I am a perfectionist / I work too hard"',
      '"I have no real weaknesses"',
      'A genuine, non-disqualifying weakness plus the concrete action you are taking about it',
      'A weakness completely unrelated to work, like a fear of heights',
    ],
    answer: [2],
    explain:
      'The question tests self-awareness, not confession. Pick something real but not fatal to the role, then spend most of your answer on the correction: "I used to over-engineer solutions before validating the requirement — now I write a one-paragraph spec and get it confirmed before I code, which caught a wrong assumption on my last project." The humble-brag answers read as evasive, and "no weaknesses" reads as no self-awareness.',
    hint: 'The weakness itself is barely being assessed. What follows it is.',
    followUp: 'What is a real weakness of yours, and what have you concretely changed about it?',
    tags: ['weakness', 'classic'],
  },
  {
    id: 'hr-4',
    world: 'hr',
    skill: 'hr.company',
    kind: 'mcq',
    difficulty: 3,
    prompt: '"Why do you want to work here?" — what separates a strong answer from a weak one?',
    choices: [
      'Mentioning the salary and job security',
      'Specific, researched detail about their product, engineering culture or a recent launch, tied to what you want to build',
      'Saying it is a great company with great people',
      'Explaining that you applied everywhere and they responded first',
    ],
    answer: [1],
    explain:
      'Specificity is the entire signal. "You are a great company" applies to every company and therefore says nothing. "I read your engineering blog post on migrating to event sourcing, and I built something similar at a much smaller scale in my final-year project" proves you did the work and gives them a thread to pull. Spend fifteen minutes on their blog, docs and recent releases before every interview.',
    hint: 'Would your answer still make sense if you swapped in a competitor\'s name? If yes, it is too generic.',
    followUp: 'Name one specific thing about this company that made you apply.',
    tags: ['motivation', 'classic'],
  },
  {
    id: 'hr-5',
    world: 'hr',
    skill: 'hr.behaviour',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Asked about a project failure, what should you emphasise most?',
    choices: [
      'That it was mostly caused by teammates or circumstances',
      'Your ownership of the decisions, what you learned, and what you now do differently',
      'That it was not really a failure when you look at it closely',
      'Technical details of the system architecture',
    ],
    answer: [1],
    explain:
      'Failure questions test ownership and learning velocity. Deflecting blame is disqualifying; denying the failure dodges the question. State plainly what went wrong, own your part in it, then spend the bulk of the answer on the changed behaviour — ideally with evidence you applied it since. Interviewers are far more comfortable with someone who has failed and adapted than with someone who claims never to have failed.',
    hint: 'They already know the project failed. What they do not know is whether you changed.',
    followUp: 'Tell me about something you shipped that did not work. What would you do differently now?',
    tags: ['failure'],
  },
  {
    id: 'hr-6',
    world: 'hr',
    skill: 'hr.negotiate',
    kind: 'mcq',
    difficulty: 4,
    prompt: '"Do you have any questions for us?" — what is the worst response?',
    choices: [
      'Asking what success in this role looks like at six months',
      'Asking about the team\'s biggest current technical challenge',
      '"No, I think everything was covered."',
      'Asking how the team handles code review and mentorship for juniors',
    ],
    answer: [2],
    explain:
      '"No questions" reads as disinterest, and it wastes the one part of the interview you fully control. Prepare three questions in advance: one about the role (what does success look like), one about the team (biggest current challenge), one about growth (how juniors are mentored). Avoid questions answerable from the careers page — that signals the opposite of research.',
    hint: 'Which option gives the interviewer no new information about you at all?',
    followUp: 'What three questions would you ask us, and what are you hoping to learn from each?',
    tags: ['closing', 'classic'],
  },
  {
    id: 'hr-7',
    world: 'hr',
    skill: 'hr.negotiate',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Asked for your expected salary as a fresher, what is the best move?',
    choices: [
      'Name the highest number you can think of',
      'Say "whatever you think is fair"',
      'Give a researched range for the role, location and your level, and note you are open to discussing the full package',
      'Refuse to answer entirely',
    ],
    answer: [2],
    explain:
      'A researched range shows you take yourself seriously and have done market homework — check Levels.fyi, Glassdoor and your college\'s past placement data first. "Whatever you think is fair" hands over all leverage; a wild number signals you have not researched. Mentioning the full package (base, bonus, equity, learning budget) keeps the conversation collaborative rather than adversarial.',
    hint: 'The answer should demonstrate preparation without painting you into a corner.',
    followUp: 'What range would you give for this role, and what is it based on?',
    tags: ['salary'],
  },
  {
    id: 'hr-8',
    world: 'hr',
    skill: 'hr.story',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'You are asked about a technology on your résumé that you barely used. Best response?',
    choices: [
      'Confidently claim deep expertise and hope they do not probe',
      'Be honest about your actual depth, describe exactly what you did build with it, and show how quickly you pick things up',
      'Say you have never heard of it',
      'Change the subject to a technology you know well',
    ],
    answer: [1],
    explain:
      'Interviewers probe résumé claims precisely to test calibration. Overclaiming collapses the moment they ask a second question, and it costs you credibility on everything else you said. "I used it for one feature — here is specifically what I built and what I did not touch" is a strong answer: it demonstrates honest self-assessment, which is a trait they are explicitly screening for. Then bridge to how you ramped up.',
    hint: 'Getting caught overclaiming does not just lose you that question.',
    followUp: 'Which item on your résumé are you *least* confident defending, and how would you frame it?',
    tags: ['honesty'],
  },
  {
    id: 'hr-9',
    world: 'hr',
    skill: 'hr.company',
    kind: 'mcq',
    difficulty: 3,
    prompt: '"Where do you see yourself in five years?" — what is the interviewer actually checking?',
    choices: [
      'Whether you can predict the future accurately',
      'Whether your goals are ambitious yet plausibly compatible with staying and growing at this company',
      'Whether you plan to start a competing business',
      'Your ability to name a specific job title',
    ],
    answer: [1],
    explain:
      'They are testing for direction and retention risk, not clairvoyance. A good answer shows growth ambition anchored in this role: deepening technical depth, taking on design ownership, mentoring. Two failure modes: no direction at all ("I have not thought about it"), and a direction that obviously routes away from the company ("doing an MBA abroad", "launching my own startup").',
    hint: 'They are hiring someone for the next few years. What worries them about a fresher?',
    tags: ['goals'],
  },
  {
    id: 'hr-10',
    world: 'hr',
    skill: 'hr.behaviour',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A teammate consistently misses deadlines and it is blocking you. What does a strong answer describe?',
    choices: [
      'Immediately escalating to the manager',
      'Silently absorbing their work to keep the project on track',
      'A direct, private conversation first to understand the cause, then escalating with context if it continues',
      'Publicly flagging it in the team channel so it gets fixed fast',
    ],
    answer: [2],
    explain:
      'They are assessing conflict handling and maturity. Escalating first signals you cannot resolve things peer-to-peer; silently absorbing the work is unsustainable and hides the problem; public callouts damage trust. The strong pattern is: talk directly and privately, seek to understand the cause, propose a concrete adjustment, and escalate *with* context only if nothing changes.',
    hint: 'Which sequence tries the lowest-drama option first without letting the problem persist?',
    followUp: 'Tell me about a real time you had friction with a teammate. What did you actually do?',
    tags: ['conflict', 'classic'],
  },
]
