import type { Question } from '../../game/types'

export const PYTHON_QUESTIONS: Question[] = [
  {
    id: 'py-1',
    world: 'python',
    skill: 'py.basics',
    kind: 'predict-output',
    difficulty: 1,
    prompt: 'What does this print?',
    code: 'print(type(5 / 2))',
    choices: ["<class 'int'>", "<class 'float'>", "<class 'decimal'>", 'SyntaxError'],
    answer: [1],
    explain:
      'In Python 3, `/` is *true division* and always returns a float — even when the result is whole. `5 / 2` is `2.5`, and `4 / 2` is `2.0`, not `2`. Use `//` for floor division when you want an int.',
    hint: 'Python 3 changed how the single-slash operator behaves compared to Python 2.',
    followUp: 'What would `5 // 2` and `-5 // 2` give you, and why is the second one surprising?',
    tags: ['operators', 'types'],
  },
  {
    id: 'py-2',
    world: 'python',
    skill: 'py.basics',
    kind: 'predict-output',
    difficulty: 2,
    prompt: 'What is the output?',
    code: 'print(0.1 + 0.2 == 0.3)\nprint(round(0.1 + 0.2, 2) == 0.3)',
    choices: ['True / True', 'False / True', 'True / False', 'False / False'],
    answer: [1],
    explain:
      'Floats are stored in binary IEEE-754, and 0.1 has no exact binary representation. `0.1 + 0.2` is actually `0.30000000000000004`, so the first comparison is False. Rounding to 2 decimals makes it exactly 0.3, so the second is True. In interviews: never compare floats with `==` — compare with a tolerance, or use `decimal.Decimal` for money.',
    hint: 'Think about how a computer stores a number like 0.1 in binary.',
    followUp: 'How would you compare two floats safely in production code?',
    tags: ['floats', 'gotcha'],
  },
  {
    id: 'py-3',
    world: 'python',
    skill: 'py.basics',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Which of these evaluates to `True`?',
    choices: ['bool("")', 'bool([])', 'bool("False")', 'bool(0.0)'],
    answer: [2],
    explain:
      'Any non-empty string is truthy — including the string `"False"`, which trips people up constantly. Empty containers (`""`, `[]`, `{}`, `set()`), zero of any numeric type, and `None` are all falsy. Everything else is truthy by default.',
    hint: 'Truthiness is about emptiness, not about what the characters spell.',
    tags: ['truthiness'],
  },
  {
    id: 'py-4',
    world: 'python',
    skill: 'py.basics',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'When is it correct to use `is` instead of `==`?',
    choices: [
      'When comparing two strings for equal content',
      'When comparing against `None`, `True` or `False`',
      'When comparing two integers for equal value',
      'Whenever you want a faster comparison',
    ],
    answer: [1],
    explain:
      '`is` compares *identity* — whether two names point at the same object in memory. `==` compares *value*. Since `None`, `True` and `False` are singletons, `x is None` is the idiomatic and correct check. Using `is` on strings or ints appears to work because of interning caches, then breaks silently on larger values.',
    hint: 'One of these compares memory addresses; only one kind of value is guaranteed to be a singleton.',
    followUp: 'Why does `a = 256; b = 256; a is b` give True but the same code with 257 gives False?',
    tags: ['identity', 'gotcha'],
  },
  {
    id: 'py-5',
    world: 'python',
    skill: 'py.collections',
    kind: 'predict-output',
    difficulty: 2,
    prompt: 'What does this print?',
    code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)',
    choices: ['[1, 2, 3]', '[1, 2, 3, 4]', '[4, 1, 2, 3]', 'TypeError'],
    answer: [1],
    explain:
      '`b = a` binds a second name to the *same* list object — it does not copy. Mutating through either name is visible through both. To get an independent copy use `b = a[:]`, `b = list(a)`, or `copy.deepcopy(a)` when the list contains nested mutable objects.',
    hint: 'Assignment in Python binds names to objects. Ask yourself how many list objects exist here.',
    followUp: 'What is the difference between a shallow copy and a deep copy, and when does it actually matter?',
    tags: ['references', 'mutability'],
  },
  {
    id: 'py-6',
    world: 'python',
    skill: 'py.collections',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'You need to check membership of 100,000 items inside a tight loop. Which container?',
    choices: ['list', 'tuple', 'set', 'It makes no measurable difference'],
    answer: [2],
    explain:
      'Membership testing (`x in c`) is O(n) for lists and tuples — Python scans element by element. Sets and dict keys are hash tables, so lookup is O(1) on average. Swapping a list for a set here turns an O(n·m) loop into O(n), which is one of the highest-value one-line optimisations in interviews.',
    hint: 'Which of these is backed by a hash table?',
    followUp: 'What requirement must the elements satisfy to go into a set, and why?',
    tags: ['complexity', 'sets'],
  },
  {
    id: 'py-7',
    world: 'python',
    skill: 'py.collections',
    kind: 'predict-output',
    difficulty: 3,
    prompt: 'What is printed?',
    code: 't = (1, 2, [3, 4])\nt[2].append(5)\nprint(t)',
    choices: ['(1, 2, [3, 4])', '(1, 2, [3, 4, 5])', 'TypeError: tuple is immutable', 'AttributeError'],
    answer: [1],
    explain:
      'Tuple immutability is *shallow*. The tuple guarantees its slots always reference the same objects — it says nothing about whether those objects can change internally. The list at index 2 is still mutable, so appending works. This is also why such a tuple is unhashable and cannot be a dict key.',
    hint: 'What exactly does the tuple promise not to change — the references, or the objects behind them?',
    tags: ['tuples', 'mutability', 'gotcha'],
  },
  {
    id: 'py-8',
    world: 'python',
    skill: 'py.collections',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What does `dict.get(key, default)` do that `dict[key]` does not?',
    choices: [
      'It is significantly faster',
      'It returns the default instead of raising KeyError when the key is absent',
      'It inserts the default into the dictionary',
      'It searches values as well as keys',
    ],
    answer: [1],
    explain:
      '`get` is the safe accessor: missing key returns the default (or `None`) rather than raising `KeyError`. Note it does *not* insert — if you want the default written back, use `setdefault` or a `collections.defaultdict`.',
    hint: 'Think about what happens on a missing key, not about speed.',
    tags: ['dicts'],
  },
  {
    id: 'py-9',
    world: 'python',
    skill: 'py.strings',
    kind: 'predict-output',
    difficulty: 2,
    prompt: 'What is the output?',
    code: 's = "placement"\nprint(s[::-1])\nprint(s[2:5])',
    choices: ['tnemecalp / ace', 'placement / ace', 'tnemecalp / lac', 'tnemecalp / acem'],
    answer: [0],
    explain:
      '`s[::-1]` uses a step of -1, walking the string backwards — the idiomatic Python reverse. `s[2:5]` takes indices 2, 3, 4 (start inclusive, stop exclusive) which is `"ace"` from p-l-a-c-e-m-e-n-t.',
    hint: 'Slice syntax is [start:stop:step], and stop is never included.',
    followUp: 'Reversing a string this way is O(n) space. How would you reverse one in place in a language with mutable strings?',
    tags: ['slicing'],
  },
  {
    id: 'py-10',
    world: 'python',
    skill: 'py.strings',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Building a big string by repeatedly doing `result += chunk` inside a loop is discouraged. Why?',
    choices: [
      'It raises a MemoryError above 1000 iterations',
      'Strings are immutable, so each += allocates a new string — the loop becomes O(n²)',
      'It silently truncates at 65535 characters',
      'It only works with ASCII input',
    ],
    answer: [1],
    explain:
      'Python strings are immutable, so `result += chunk` builds a brand-new string and copies everything already accumulated. Over n iterations that is 1 + 2 + … + n character copies — quadratic. The fix is to collect pieces in a list and `"".join(parts)` once, which is linear. (CPython has an opportunistic optimisation for this case, but you cannot rely on it and interviewers expect the join answer.)',
    hint: 'Count how many characters get copied in total across all iterations.',
    followUp: 'What is the equivalent idiom in Java, and why does it exist?',
    tags: ['complexity', 'strings'],
  },
  {
    id: 'py-11',
    world: 'python',
    skill: 'py.functions',
    kind: 'predict-output',
    difficulty: 4,
    prompt: 'What does this print?',
    code: 'def add(item, bucket=[]):\n    bucket.append(item)\n    return bucket\n\nprint(add(1))\nprint(add(2))',
    choices: ['[1] / [2]', '[1] / [1, 2]', '[1] / []', 'TypeError on the second call'],
    answer: [1],
    explain:
      'The classic mutable-default trap. Default arguments are evaluated **once**, when the function is defined — not on each call. Both calls share the same list object, so it accumulates. The fix: `def add(item, bucket=None): bucket = [] if bucket is None else bucket`. Interviewers love this one because it separates people who have read the docs from people who have been bitten in production.',
    hint: 'When exactly does Python evaluate the expression that produces the default value?',
    followUp: 'Show me how you would rewrite this function correctly.',
    tags: ['defaults', 'gotcha', 'classic'],
  },
  {
    id: 'py-12',
    world: 'python',
    skill: 'py.functions',
    kind: 'predict-output',
    difficulty: 4,
    prompt: 'What does this print?',
    code: 'fns = [lambda: i for i in range(3)]\nprint([f() for f in fns])',
    choices: ['[0, 1, 2]', '[2, 2, 2]', '[3, 3, 3]', '[None, None, None]'],
    answer: [1],
    explain:
      'Late binding. Each lambda closes over the *variable* `i`, not its value at creation time. By the time any lambda is called, the comprehension has finished and `i` is 2 — so all three return 2. Fix it by capturing the value with a default argument: `lambda i=i: i`.',
    hint: 'When is `i` actually looked up — when the lambda is created, or when it is called?',
    followUp: 'What are two different ways to fix this so the list is [0, 1, 2]?',
    tags: ['closures', 'gotcha'],
  },
  {
    id: 'py-13',
    world: 'python',
    skill: 'py.functions',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'In `def f(*args, **kwargs)`, what are `args` and `kwargs`?',
    choices: [
      'args is a list, kwargs is a set',
      'args is a tuple of positional arguments, kwargs is a dict of keyword arguments',
      'Both are dicts',
      'args is a dict of positional arguments, kwargs is a tuple',
    ],
    answer: [1],
    explain:
      '`*args` collects extra positional arguments into a **tuple**; `**kwargs` collects extra keyword arguments into a **dict**. The names are convention only — the `*` and `**` do the work. This is the standard way to write decorators and wrappers that forward arbitrary arguments.',
    hint: 'One collects things passed by position, the other by name. Which data structures fit each?',
    tags: ['functions'],
  },
  {
    id: 'py-14',
    world: 'python',
    skill: 'py.oop',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the difference between `__str__` and `__repr__`?',
    choices: [
      'They are aliases for the same method',
      '__str__ is for end users and readability; __repr__ is for developers and should be unambiguous',
      '__repr__ is only called on subclasses',
      '__str__ must return bytes',
    ],
    answer: [1],
    explain:
      '`__str__` powers `str(obj)` and `print(obj)` — make it human-friendly. `__repr__` powers `repr(obj)` and what you see in the REPL or inside a container; it should ideally be unambiguous and, where practical, look like valid code that recreates the object. If you only define one, define `__repr__` — Python falls back to it for `str()`.',
    hint: 'One is aimed at your users, the other at you while debugging at 2am.',
    tags: ['dunder'],
  },
  {
    id: 'py-15',
    world: 'python',
    skill: 'py.oop',
    kind: 'predict-output',
    difficulty: 4,
    prompt: 'What does this print?',
    code: 'class A:\n    tags = []\n\na1 = A()\na2 = A()\na1.tags.append("x")\nprint(a2.tags)',
    choices: ['[]', "['x']", 'AttributeError', 'None'],
    answer: [1],
    explain:
      '`tags` is a **class attribute** — one list shared by every instance. Mutating it through `a1` is visible through `a2`. Note the subtlety: `a1.tags = ["x"]` (rebinding) would instead create an instance attribute and leave `a2` untouched. Mutation and rebinding behave completely differently here. Per-instance state belongs in `__init__`.',
    hint: 'Where does that list actually live — on the class, or on each instance?',
    followUp: 'How would you rewrite the class so each instance gets its own tags list?',
    tags: ['classes', 'gotcha'],
  },
  {
    id: 'py-16',
    world: 'python',
    skill: 'py.advanced',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the main practical advantage of a generator over returning a list?',
    choices: [
      'Generators are always faster per element',
      'Generators produce values lazily, so memory stays O(1) instead of O(n)',
      'Generators can be indexed and sliced',
      'Generators can be iterated any number of times',
    ],
    answer: [1],
    explain:
      'A generator yields one value at a time and holds only its current state, so you can stream a 10GB file or an infinite sequence in constant memory. The trade-offs: you cannot index into it, you cannot get its length, and it is exhausted after one full pass.',
    hint: 'Think about what has to exist in memory at once in each case.',
    followUp: 'Write a generator that yields Fibonacci numbers forever. How would you take just the first ten?',
    tags: ['generators'],
  },
  {
    id: 'py-17',
    world: 'python',
    skill: 'py.advanced',
    kind: 'predict-output',
    difficulty: 4,
    prompt: 'Given the decorators below, what is the effective call order when `greet()` runs?',
    code: '@bold\n@italic\ndef greet():\n    return "hi"',
    choices: [
      'bold(italic(greet)) — italic is applied first, bold wraps outermost',
      'italic(bold(greet)) — bold is applied first',
      'They run in parallel',
      'Only the top decorator is applied',
    ],
    answer: [0],
    explain:
      'Decorators are applied bottom-up: `greet = bold(italic(greet))`. So `italic` wraps the original function first, and `bold` wraps the result. At call time execution flows top-down through the wrappers — `bold`\'s code runs first, then `italic`\'s, then the original body.',
    hint: 'Rewrite the stacked syntax as nested function calls and read it inside-out.',
    tags: ['decorators'],
  },
  {
    id: 'py-18',
    world: 'python',
    skill: 'py.advanced',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What does a `with` statement (context manager) guarantee?',
    choices: [
      'The block runs in a separate thread',
      'Cleanup (__exit__) runs even if the block raises an exception',
      'The block is retried on failure',
      'Variables inside the block are scoped to it',
    ],
    answer: [1],
    explain:
      'A context manager calls `__enter__` on entry and `__exit__` on exit — and `__exit__` is guaranteed to run whether the block finished normally, returned early, or raised. That is why `with open(f) as fh:` is the correct way to handle files: the handle closes even if your parsing blows up mid-way.',
    hint: 'Its main job relates to what happens when things go wrong.',
    followUp: 'How would you write your own context manager, either as a class or with contextlib?',
    tags: ['context-manager'],
  },

  /* ---------------------------------------------------------- shipping code */

  {
    id: 'py-19',
    world: 'python',
    skill: 'py.dev',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Why is a bare `except:` discouraged?',
    choices: [
      'It is slower than catching a specific exception',
      'It swallows everything — including KeyboardInterrupt and SystemExit — hiding bugs and making the program unkillable',
      'It only works inside functions',
      'It is a syntax error in Python 3',
    ],
    answer: [1],
    explain:
      'A bare `except:` catches `BaseException`, which includes `KeyboardInterrupt` and `SystemExit` — so Ctrl-C stops working and a genuine crash is silently turned into "everything is fine". Catch the narrowest exception you can actually handle. If you truly need a catch-all, use `except Exception:` (which excludes those two) and re-raise or log with `logging.exception()` so the traceback survives.',
    hint: 'Think about what else is an exception besides the errors your code raises.',
    followUp: 'What is the difference between `except Exception` and a bare `except`?',
    tags: ['exceptions'],
  },
  {
    id: 'py-20',
    world: 'python',
    skill: 'py.dev',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What problem does a virtual environment solve?',
    choices: [
      'It makes Python run faster',
      'It isolates each project\'s dependencies and versions so they cannot conflict system-wide',
      'It compiles Python to machine code',
      'It encrypts your source code',
    ],
    answer: [1],
    explain:
      'Two projects can need incompatible versions of the same library. A virtual environment gives each its own `site-packages`, so installing Django 4 for one project cannot break another that needs Django 3. Create one with `python -m venv .venv`, activate it, then `pip install -r requirements.txt`. Interviewers ask this to check you have actually built something rather than only solved exercises.',
    hint: 'The problem appears the moment you have two projects on one machine.',
    followUp: 'What goes in requirements.txt, and how do you generate it?',
    tags: ['tooling'],
  },
  {
    id: 'py-21',
    world: 'python',
    skill: 'py.dev',
    kind: 'predict-output',
    difficulty: 4,
    prompt: 'What does this print?',
    code: 'def f():\n    try:\n        return "try"\n    finally:\n        print("finally")\n\nprint(f())',
    choices: ['try', 'finally\\ntry', 'try\\nfinally', 'finally only'],
    answer: [1],
    explain:
      '`finally` runs before the function actually returns — even though the return value was already computed. So "finally" prints first, then the returned "try". This guarantee is exactly why `finally` (and `with`) are the right places for cleanup: they run on the success path, the exception path, and the early-return path alike. A `return` inside `finally` would additionally *discard* the original return value, which is a real bug worth knowing.',
    hint: 'The return value is computed first, but something still has to happen before control leaves the function.',
    followUp: 'What happens if you put a `return` inside the `finally` block?',
    tags: ['exceptions', 'gotcha'],
  },
  {
    id: 'py-22',
    world: 'python',
    skill: 'py.dev',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the purpose of `if __name__ == "__main__":`?',
    choices: [
      'It marks the entry point required by the interpreter',
      'It runs that block only when the file is executed directly, not when it is imported as a module',
      'It makes the code run faster',
      'It declares the file to be a package',
    ],
    answer: [1],
    explain:
      'Python sets `__name__` to `"__main__"` in the file you ran, and to the module\'s name when it is imported. The guard means a file can expose reusable functions *and* have a runnable CLI without the CLI firing on every import. Without it, importing your script executes its top-level code as a side effect — which breaks testing, since a test runner imports the module.',
    hint: 'The value of `__name__` differs depending on how the file was loaded.',
    tags: ['modules'],
  },
  {
    id: 'py-23',
    world: 'python',
    skill: 'py.dev',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What does the Global Interpreter Lock (GIL) mean for concurrency in CPython?',
    choices: [
      'Python cannot do concurrency at all',
      'Only one thread executes Python bytecode at a time, so threads help with I/O-bound work but not CPU-bound work',
      'The GIL makes threads faster than processes',
      'The GIL only affects Python 2',
    ],
    answer: [1],
    explain:
      'The GIL lets only one thread run Python bytecode at a time. For **I/O-bound** work — network calls, disk, database — threads still help, because the GIL is released while waiting. For **CPU-bound** work they do not: four threads doing maths run no faster than one. Use `multiprocessing` (separate interpreters, real parallelism) or a native library like NumPy that releases the GIL. This is a very common senior-ish follow-up to "do you know threading?"',
    hint: 'Ask what a thread is doing while it waits for a network response versus while it multiplies numbers.',
    followUp: 'Your job is CPU-bound. What would you reach for instead of threads?',
    tags: ['concurrency', 'classic'],
  },
  {
    id: 'py-24',
    world: 'python',
    skill: 'py.dev',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Why prefer `logging` over `print()` in production code?',
    choices: [
      'print is deprecated in Python 3',
      'logging gives you severity levels, timestamps, module names and configurable destinations without editing call sites',
      'logging is faster',
      'print cannot output to a file',
    ],
    answer: [1],
    explain:
      'With `logging` you tag each message by severity (DEBUG through CRITICAL) and decide *later*, from configuration, what to show and where to send it — console in development, a file or aggregator in production — without touching a single call site. You also get timestamps and module names for free, and `logger.exception()` captures the full traceback. `print` gives you none of that and always goes to stdout.',
    hint: 'The difference shows up when you need to change what gets recorded without changing the code.',
    tags: ['tooling'],
  },
]
