import type { Question } from '../../game/types'

export const SQL_QUESTIONS: Question[] = [
  {
    id: 'sql-1',
    world: 'sql',
    skill: 'sql.select',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Which predicate correctly finds rows where `manager_id` has no value?',
    choices: ['WHERE manager_id = NULL', 'WHERE manager_id IS NULL', 'WHERE manager_id == NULL', "WHERE manager_id = 'NULL'"],
    answer: [1],
    explain:
      'NULL means "unknown", and any comparison *to* an unknown yields unknown — not true. So `= NULL` never matches a row, silently returning zero results instead of erroring. You must use `IS NULL` / `IS NOT NULL`. This three-valued logic is the single most common source of quietly-wrong SQL.',
    hint: 'NULL is not a value you can equal — it is the absence of one.',
    followUp: 'What does `COUNT(manager_id)` return compared to `COUNT(*)` when some rows are NULL?',
    tags: ['null', 'classic'],
  },
  {
    id: 'sql-2',
    world: 'sql',
    skill: 'sql.select',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'In what order does the database logically process these clauses?',
    code: 'SELECT ... FROM ... WHERE ... GROUP BY ... HAVING ... ORDER BY ... LIMIT ...',
    choices: [
      'SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT',
      'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT',
      'FROM → SELECT → WHERE → GROUP BY → HAVING → LIMIT → ORDER BY',
      'WHERE → FROM → GROUP BY → SELECT → HAVING → ORDER BY → LIMIT',
    ],
    answer: [1],
    explain:
      'Logical processing order is FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. This explains two things people find mysterious: why you cannot reference a `SELECT` alias in `WHERE` (the alias does not exist yet), and why you *can* reference it in `ORDER BY` (by then it does).',
    hint: 'The rows have to be fetched and filtered before anything can be selected from them.',
    followUp: 'Given that order, why does WHERE reject aggregate functions but HAVING accept them?',
    tags: ['order-of-execution', 'classic'],
  },
  {
    id: 'sql-3',
    world: 'sql',
    skill: 'sql.joins',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'You want every customer, including those with zero orders. Which join?',
    choices: [
      'INNER JOIN orders',
      'LEFT JOIN orders',
      'RIGHT JOIN orders',
      'CROSS JOIN orders',
    ],
    answer: [1],
    explain:
      'A LEFT JOIN keeps every row from the left table (customers) and fills the right side with NULLs where there is no match. INNER JOIN would silently drop exactly the customers you are trying to find. To then isolate *only* the customers with no orders, add `WHERE o.id IS NULL` — the anti-join pattern.',
    hint: 'Which join preserves unmatched rows from the first table?',
    followUp: 'Write the query that returns only customers who have never ordered.',
    tags: ['joins'],
  },
  {
    id: 'sql-4',
    world: 'sql',
    skill: 'sql.joins',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Table A has 5 rows, table B has 3 rows. `SELECT * FROM A CROSS JOIN B` returns how many rows?',
    choices: ['3', '5', '8', '15'],
    answer: [3],
    explain:
      'A cross join is the Cartesian product — every row of A paired with every row of B, so 5 × 3 = 15. This is also what you accidentally get when you list two tables in FROM and forget the join condition, which is why a query that should return thousands of rows suddenly returns millions.',
    hint: 'Every row on the left pairs with every row on the right.',
    tags: ['joins'],
  },
  {
    id: 'sql-5',
    world: 'sql',
    skill: 'sql.aggregate',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the difference between `WHERE` and `HAVING`?',
    choices: [
      'They are interchangeable',
      'WHERE filters rows before grouping; HAVING filters groups after aggregation',
      'HAVING is only valid with ORDER BY',
      'WHERE works on numbers, HAVING on strings',
    ],
    answer: [1],
    explain:
      'WHERE runs before GROUP BY, so it filters individual rows and cannot see aggregate results. HAVING runs after, so it can filter on `COUNT(*)`, `SUM(x)` and friends. Performance tip: filter as much as possible in WHERE — fewer rows reaching the grouping stage means less work.',
    hint: 'One of them runs before the rows are collapsed into groups.',
    followUp: 'Write a query returning departments with more than 10 employees earning above 50k.',
    tags: ['aggregation', 'classic'],
  },
  {
    id: 'sql-6',
    world: 'sql',
    skill: 'sql.aggregate',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A `salary` column has 10 rows, 3 of which are NULL. What does `COUNT(salary)` return?',
    choices: ['10', '7', '3', 'NULL'],
    answer: [1],
    explain:
      '`COUNT(column)` ignores NULLs and counts only non-null values — so 7. `COUNT(*)` counts rows regardless and would return 10. The same rule applies to `SUM` and `AVG`: they skip NULLs entirely, which means `AVG(salary)` here divides by 7, not 10. That distinction changes reported averages in real reports.',
    hint: 'Aggregate functions have an opinion about missing values.',
    followUp: 'How would you make AVG treat those NULLs as zero instead?',
    tags: ['aggregation', 'null'],
  },
  {
    id: 'sql-7',
    world: 'sql',
    skill: 'sql.subquery',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What does this return?',
    code: 'SELECT name FROM employees e\nWHERE salary > (\n  SELECT AVG(salary) FROM employees\n  WHERE dept_id = e.dept_id\n);',
    choices: [
      'Everyone earning above the company-wide average',
      'Everyone earning above the average of their own department',
      'The single highest earner per department',
      'A syntax error — subqueries cannot reference the outer table',
    ],
    answer: [1],
    explain:
      'This is a **correlated subquery**: the inner query references `e.dept_id` from the outer row, so it is re-evaluated per row with that row\'s department. The result is everyone paid above their own department average. It is correct but can be slow on large tables — a window function (`AVG(salary) OVER (PARTITION BY dept_id)`) usually computes the same thing in a single pass.',
    hint: 'Look at what the inner WHERE clause refers to. Is it fixed, or does it change per outer row?',
    followUp: 'Rewrite this with a window function and explain why it is usually faster.',
    tags: ['subquery', 'correlated', 'classic'],
  },
  {
    id: 'sql-8',
    world: 'sql',
    skill: 'sql.subquery',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the main advantage of a CTE (`WITH ... AS`) over a nested subquery?',
    choices: [
      'CTEs are always faster',
      'Readability, reuse of the same result set, and support for recursion',
      'CTEs bypass indexes',
      'CTEs can modify data, subqueries cannot',
    ],
    answer: [1],
    explain:
      'CTEs name an intermediate result, so a deeply nested query becomes a readable top-to-bottom sequence of steps. You can reference the same CTE multiple times in one query, and `WITH RECURSIVE` handles hierarchies like org charts or category trees. Performance is usually similar — most modern optimisers inline them.',
    hint: 'Think about the human reading the query as much as the engine running it.',
    followUp: 'How would you use a recursive CTE to find every employee under a given manager?',
    tags: ['cte'],
  },
  {
    id: 'sql-9',
    world: 'sql',
    skill: 'sql.window',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Salaries are 100, 100, 90. What does `RANK()` produce versus `DENSE_RANK()`?',
    choices: [
      'RANK: 1,1,2 — DENSE_RANK: 1,1,3',
      'RANK: 1,1,3 — DENSE_RANK: 1,1,2',
      'Both give 1,1,2',
      'Both give 1,2,3',
    ],
    answer: [1],
    explain:
      '`RANK()` leaves gaps after ties: two firsts, then third place — 1, 1, 3. `DENSE_RANK()` does not skip: 1, 1, 2. `ROW_NUMBER()` ignores ties entirely and gives 1, 2, 3. Picking the wrong one is the classic bug in "find the Nth highest salary" — with duplicates, `ROW_NUMBER` gives an answer that is simply incorrect.',
    hint: 'One of them behaves like Olympic medals when two athletes tie for gold.',
    followUp: 'Write the query for the 2nd-highest distinct salary. Which function did you pick and why?',
    tags: ['window', 'classic'],
  },
  {
    id: 'sql-10',
    world: 'sql',
    skill: 'sql.window',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What does `PARTITION BY` do in a window function?',
    choices: [
      'Physically splits the table into shards on disk',
      'Divides rows into groups within which the window function is computed independently',
      'Filters out rows that do not match',
      'Sorts the final output',
    ],
    answer: [1],
    explain:
      'PARTITION BY resets the window calculation for each group — `ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC)` numbers employees starting from 1 within every department. Unlike GROUP BY it does **not** collapse rows: you keep every original row and gain an extra computed column alongside it.',
    hint: 'It groups for the purposes of the calculation — but does it reduce the row count?',
    followUp: 'How would you use this to get the top 3 earners in each department?',
    tags: ['window'],
  },
  {
    id: 'sql-11',
    world: 'sql',
    skill: 'sql.select',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Which removes duplicate rows from a result set?',
    choices: ['UNIQUE', 'DISTINCT', 'GROUP BY only', 'FILTER'],
    answer: [1],
    explain:
      '`SELECT DISTINCT` removes duplicate rows across all selected columns. `UNIQUE` is a table constraint, not a query keyword. `GROUP BY` also deduplicates as a side effect, but its actual purpose is enabling aggregation — reaching for it just to dedupe signals confusion in an interview.',
    hint: 'One of these is a query keyword; another is a schema constraint.',
    tags: ['select'],
  },
  {
    id: 'sql-12',
    world: 'sql',
    skill: 'sql.joins',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'An `employees` table has `id` and `manager_id` (pointing at another employee). How do you list each employee alongside their manager\'s name?',
    choices: [
      'A CROSS JOIN on the same table',
      'A SELF JOIN — join employees to itself with two aliases',
      'A UNION of the table with itself',
      'It requires a second table; it cannot be done',
    ],
    answer: [1],
    explain:
      'Join the table to itself under two aliases: `FROM employees e LEFT JOIN employees m ON e.manager_id = m.id`. Use LEFT rather than INNER so the CEO — who has a NULL manager_id — still appears. Self-joins come up constantly for hierarchies, and forgetting the LEFT is the standard mistake.',
    hint: 'Nothing stops a table from appearing twice in one query, as long as you give each appearance its own name.',
    followUp: 'Why did you choose LEFT JOIN here rather than INNER JOIN?',
    tags: ['joins', 'self-join', 'classic'],
  },
  {
    id: 'sql-13',
    world: 'sql',
    skill: 'sql.aggregate',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is wrong with this query in a strict SQL mode?',
    code: 'SELECT dept_id, name, COUNT(*)\nFROM employees\nGROUP BY dept_id;',
    choices: [
      'COUNT(*) cannot appear with GROUP BY',
      '`name` is neither grouped nor aggregated, so which value should it show?',
      'GROUP BY must come before SELECT',
      'Nothing is wrong',
    ],
    answer: [1],
    explain:
      'Every non-aggregated column in the SELECT list must appear in GROUP BY. Here a department has many employees, so there is no single well-defined `name` for the group. Postgres and strict-mode MySQL reject this; older MySQL defaults silently picked an arbitrary row, producing plausible-looking but meaningless output.',
    hint: 'After grouping by department, how many names does each row represent?',
    tags: ['aggregation', 'gotcha'],
  },
  {
    id: 'sql-14',
    world: 'sql',
    skill: 'sql.subquery',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'For checking whether *any* matching row exists, which is generally preferred?',
    choices: [
      'COUNT(*) > 0 in a subquery',
      'EXISTS (SELECT 1 FROM ...)',
      'SELECT * and check the row count in the application',
      'They perform identically in all engines',
    ],
    answer: [1],
    explain:
      '`EXISTS` short-circuits — the engine can stop at the first matching row. `COUNT(*) > 0` forces a full count of every match before the comparison. On a table with millions of matching rows this is the difference between an instant answer and a table scan.',
    hint: 'To answer "does at least one exist?", how many rows do you actually need to look at?',
    tags: ['subquery', 'performance'],
  },
]
