import type { Question } from '../../game/types'

export const OS_QUESTIONS: Question[] = [
  {
    id: 'os-1',
    world: 'os',
    skill: 'os.process',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What is the key difference between a process and a thread?',
    choices: [
      'Threads are always faster than processes',
      'Processes have separate memory spaces; threads within a process share one',
      'A process can only contain one thread',
      'Threads are scheduled by the application, processes by the OS',
    ],
    answer: [1],
    explain:
      'Each process gets its own address space, so processes are isolated — one crashing does not corrupt another. Threads inside a process share the heap and globals, which makes communication cheap and context switching fast, but means you must synchronise access or face race conditions. That trade-off — isolation versus cheap sharing — is the whole answer.',
    hint: 'Think about what happens to memory when you create each one.',
    followUp: 'Given that, when would you choose multiprocessing over multithreading?',
    tags: ['process', 'classic'],
  },
  {
    id: 'os-2',
    world: 'os',
    skill: 'os.process',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is a zombie process?',
    choices: [
      'A process consuming 100% CPU in an infinite loop',
      'A terminated child whose exit status the parent has not yet collected',
      'A process with no parent',
      'A process swapped entirely to disk',
    ],
    answer: [1],
    explain:
      'A zombie has finished executing but its entry stays in the process table until the parent calls `wait()` to read its exit status. It holds no memory or CPU — just a PID slot. The related term is an **orphan**: a process whose parent died first, which gets re-parented to init/systemd and reaped automatically.',
    hint: 'It is already dead. What is still hanging around, and who is supposed to clean it up?',
    followUp: 'Why are large numbers of zombies still a problem if they consume no memory?',
    tags: ['process'],
  },
  {
    id: 'os-3',
    world: 'os',
    skill: 'os.sched',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Which scheduling algorithm gives the minimum average waiting time, and what is its catch?',
    choices: [
      'FCFS — but it needs a priority queue',
      'Shortest Job First — but it needs to know burst times in advance and can starve long jobs',
      'Round Robin — but only with a very large quantum',
      'Priority scheduling — but it requires preemption',
    ],
    answer: [1],
    explain:
      'SJF is provably optimal for average waiting time. Two practical problems: you rarely know a job\'s CPU burst ahead of time (real schedulers *estimate* it via exponential averaging of past bursts), and a stream of short jobs can starve a long one indefinitely. Ageing — gradually raising a waiting job\'s priority — is the standard fix.',
    hint: 'Putting the quickest task first minimises everyone else\'s wait. What do you need to know to do that?',
    followUp: 'What is convoy effect, and which algorithm suffers from it worst?',
    tags: ['scheduling', 'classic'],
  },
  {
    id: 'os-4',
    world: 'os',
    skill: 'os.sched',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'In Round Robin, what happens if the time quantum is set too small?',
    choices: [
      'Long processes starve',
      'Context-switching overhead dominates and throughput drops',
      'It degenerates into FCFS',
      'Nothing — smaller is always better for responsiveness',
    ],
    answer: [1],
    explain:
      'Every quantum expiry triggers a context switch, which costs real time saving and restoring registers and flushing caches. Too small and the CPU spends more time switching than working. Too large and Round Robin degenerates into FCFS. The usual rule of thumb: pick a quantum where ~80% of bursts finish within it.',
    hint: 'What does the CPU have to do every single time the quantum expires?',
    tags: ['scheduling'],
  },
  {
    id: 'os-5',
    world: 'os',
    skill: 'os.sync',
    kind: 'multi',
    difficulty: 4,
    prompt: 'Which conditions must ALL hold simultaneously for deadlock to occur? (Select all)',
    choices: ['Mutual exclusion', 'Hold and wait', 'Preemption is allowed', 'Circular wait', 'No preemption'],
    answer: [0, 1, 3, 4],
    explain:
      'Coffman\'s four conditions: **mutual exclusion** (a resource is non-shareable), **hold and wait** (a process holds one resource while requesting another), **no preemption** (resources cannot be forcibly taken), and **circular wait** (a cycle in the wait-for graph). All four must hold — so breaking any single one prevents deadlock, which is exactly how prevention strategies work. Note option 3 is the *opposite* of a required condition.',
    hint: 'There are four, and one of the listed options is the negation of a real condition.',
    followUp: 'Pick one condition and describe a concrete strategy for breaking it.',
    tags: ['deadlock', 'classic'],
  },
  {
    id: 'os-6',
    world: 'os',
    skill: 'os.sync',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is the difference between a mutex and a semaphore?',
    choices: [
      'They are the same thing with different names',
      'A mutex allows one holder and has ownership; a counting semaphore permits N concurrent holders and has none',
      'A semaphore can only be used between processes',
      'A mutex cannot block',
    ],
    answer: [1],
    explain:
      'A mutex is a locking mechanism: one holder at a time, and crucially it has **ownership** — only the thread that locked it may unlock it. A counting semaphore is a signalling mechanism holding a count of available units; any thread may signal it, which makes it suitable for producer-consumer coordination. A binary semaphore looks like a mutex but lacks the ownership guarantee.',
    hint: 'One of them cares about *who* releases it.',
    followUp: 'Which would you use to let at most 5 threads into a connection pool?',
    tags: ['sync', 'classic'],
  },
  {
    id: 'os-7',
    world: 'os',
    skill: 'os.memory',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What is thrashing?',
    choices: [
      'A process writing to another process\'s memory',
      'The system spending more time paging in and out than executing instructions',
      'Two threads deadlocking on the same mutex',
      'Fragmentation of the heap over time',
    ],
    answer: [1],
    explain:
      'Thrashing occurs when the degree of multiprogramming is too high for available physical memory: each process\'s working set does not fit, so every process constantly faults, evicting pages another process immediately needs. CPU utilisation collapses. Fixes: reduce the multiprogramming level, use working-set or page-fault-frequency models, or add RAM.',
    hint: 'The disk light is on constantly and the CPU is nearly idle. What is happening?',
    followUp: 'Ironically, a naive scheduler responds to low CPU utilisation by admitting *more* processes. Why does that make it worse?',
    tags: ['memory'],
  },
  {
    id: 'os-8',
    world: 'os',
    skill: 'os.memory',
    kind: 'mcq',
    difficulty: 4,
    prompt: "Belady's anomaly — more page frames producing *more* page faults — affects which algorithm?",
    choices: ['LRU', 'FIFO', 'Optimal (OPT)', 'All page replacement algorithms'],
    answer: [1],
    explain:
      'FIFO can exhibit Belady\'s anomaly because it ignores usage — adding a frame can change the eviction order in a way that evicts a page right before it is needed. LRU and OPT are **stack algorithms**: the set of pages held with n frames is always a subset of the set held with n+1 frames, which makes the anomaly impossible for them.',
    hint: 'The vulnerable algorithm is the one that pays no attention to whether a page is actually being used.',
    tags: ['memory', 'classic'],
  },
  {
    id: 'os-9',
    world: 'os',
    skill: 'os.memory',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What problem does virtual memory solve?',
    choices: [
      'It makes RAM physically faster',
      'It lets programs use an address space larger than physical RAM, with isolation between processes',
      'It eliminates the need for a page table',
      'It removes the need for a hard disk',
    ],
    answer: [1],
    explain:
      'Virtual memory gives each process a private, contiguous-looking address space that the MMU maps to scattered physical frames — with parts spilled to disk. That buys three things: programs larger than RAM, isolation (process A literally cannot name process B\'s memory), and simpler compilation since every program can assume it starts at address 0.',
    hint: 'Think about both size and safety.',
    followUp: 'What is a TLB, and why would virtual memory be unusably slow without one?',
    tags: ['memory'],
  },
  {
    id: 'os-10',
    world: 'os',
    skill: 'os.filesys',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What does an inode store?',
    choices: [
      'The file name and its contents',
      'File metadata and pointers to data blocks — but not the file name',
      'Only the directory hierarchy',
      'The file name and nothing else',
    ],
    answer: [1],
    explain:
      'An inode holds size, permissions, owner, timestamps, link count and block pointers. The **name** lives in the directory entry, which maps a name to an inode number. That separation is exactly why hard links work: several names can point to one inode, and the file survives until the link count hits zero.',
    hint: 'If the name were in the inode, hard links could not exist. What does that tell you?',
    followUp: 'What is the difference between a hard link and a symbolic link?',
    tags: ['filesystem'],
  },
  {
    id: 'os-11',
    world: 'os',
    skill: 'os.process',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'What does a context switch actually involve?',
    choices: [
      'Only swapping the program counter',
      'Saving the current process state (registers, PC, stack pointer) to its PCB and loading another\'s',
      'Copying the entire process memory to disk',
      'Restarting the process from the beginning',
    ],
    answer: [1],
    explain:
      'The kernel saves the CPU register set, program counter and stack pointer into the current process\'s PCB, then loads the next process\'s saved state. It also switches the memory mapping, which typically flushes the TLB — often the most expensive part. Context switching is pure overhead: the system does no useful work during it.',
    hint: 'The CPU has one set of registers. What has to happen to them before another process can run?',
    tags: ['process'],
  },
  {
    id: 'os-12',
    world: 'os',
    skill: 'os.sync',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Two threads run `counter += 1` a thousand times each. Final value is often below 2000. Why?',
    choices: [
      'Integer overflow',
      '`counter += 1` is not atomic — it is read, add, write, and updates get lost when interleaved',
      'The compiler optimised the loop away',
      'The OS randomly drops increments under load',
    ],
    answer: [1],
    explain:
      'A read-modify-write is three separate operations. Both threads can read the same value, both increment it locally, and both write back the same result — one increment vanishes. This is a **lost update** race condition. Fix it with a mutex, an atomic increment instruction, or by giving each thread its own counter and summing at the end.',
    hint: 'Break that one line into the machine-level steps it actually compiles to.',
    followUp: 'Would declaring the variable `volatile` fix this? Why or why not?',
    tags: ['sync', 'race-condition', 'classic'],
  },
]

export const NET_QUESTIONS: Question[] = [
  {
    id: 'net-1',
    world: 'networking',
    skill: 'net.model',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'At which OSI layer does a router primarily operate?',
    choices: ['Layer 2 (Data Link)', 'Layer 3 (Network)', 'Layer 4 (Transport)', 'Layer 7 (Application)'],
    answer: [1],
    explain:
      'Routers forward packets based on IP addresses, which is Layer 3. Switches work at Layer 2 using MAC addresses; hubs are Layer 1 and simply repeat electrical signals. A common follow-up: load balancers exist at both L4 (routing by IP and port) and L7 (routing by URL path or headers).',
    hint: 'What kind of address does a router read to decide where to send something?',
    tags: ['osi'],
  },
  {
    id: 'net-2',
    world: 'networking',
    skill: 'net.transport',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Which are true of TCP but NOT UDP? (Select all)',
    choices: [
      'Guaranteed, ordered delivery',
      'Connection-oriented with a handshake',
      'Lower latency and less overhead',
      'Flow control and congestion control',
    ],
    answer: [0, 1, 3],
    explain:
      'TCP provides reliable ordered delivery, a three-way handshake, and flow plus congestion control — all of which cost header bytes and round-trips. UDP omits every guarantee, which is exactly why it is the lower-latency option and why it powers live video, gaming and DNS. Option 3 describes UDP.',
    hint: 'Three of these are features you pay for with overhead. The fourth is what you get by *not* paying.',
    followUp: 'Video calls use UDP. What happens when a packet is lost, and why is that acceptable there?',
    tags: ['tcp', 'udp', 'classic'],
  },
  {
    id: 'net-3',
    world: 'networking',
    skill: 'net.transport',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Why does TCP use a *three*-way handshake rather than two?',
    choices: [
      'To transfer the first data packet',
      'So both sides confirm the other can send *and* receive, and both initial sequence numbers are acknowledged',
      'Because IP requires three packets minimum',
      'To negotiate encryption keys',
    ],
    answer: [1],
    explain:
      'SYN → SYN-ACK → ACK. The client proves it can send and the server received; the server\'s SYN-ACK proves the same in reverse; the final ACK confirms the server\'s sequence number arrived. Two packets would leave the server unsure whether its own sequence number was received — you cannot establish reliable bidirectional state in fewer.',
    hint: 'Each side needs to know its own sequence number was acknowledged. Count the confirmations.',
    followUp: 'Connection teardown takes four steps rather than three. Why the asymmetry?',
    tags: ['tcp', 'classic'],
  },
  {
    id: 'net-4',
    world: 'networking',
    skill: 'net.http',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What does HTTP status 401 mean, and how does it differ from 403?',
    choices: [
      '401 = server error; 403 = client error',
      '401 = not authenticated (who are you?); 403 = authenticated but not authorised (I know you, and no)',
      'They are interchangeable',
      '401 = resource missing; 403 = resource moved',
    ],
    answer: [1],
    explain:
      '401 Unauthorized is really "unauthenticated" — credentials are missing or invalid, so retrying with valid ones may work. 403 Forbidden means the server knows who you are and you still lack permission; retrying with the same identity will never work. The naming is a historical wart worth calling out.',
    hint: 'One is about identity, the other about permission.',
    tags: ['http'],
  },
  {
    id: 'net-5',
    world: 'networking',
    skill: 'net.http',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'You type a URL and press Enter. Which happens FIRST?',
    choices: [
      'TCP three-way handshake',
      'DNS resolution of the hostname to an IP address',
      'TLS handshake',
      'HTTP GET request is sent',
    ],
    answer: [1],
    explain:
      'You cannot open a TCP connection without an IP address, so DNS resolution comes first (after checking browser, OS and router caches). Then TCP handshake → TLS handshake if HTTPS → HTTP request → response → render. "What happens when you type a URL" is the single most common systems question in interviews; know the ordering cold.',
    hint: 'TCP needs a destination address. Where does that come from?',
    followUp: 'Walk me through the rest of it, all the way to the first pixel painted.',
    tags: ['http', 'dns', 'classic'],
  },
  {
    id: 'net-6',
    world: 'networking',
    skill: 'net.ip',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What does NAT accomplish?',
    choices: [
      'It encrypts traffic leaving the network',
      'It lets many devices share one public IP by rewriting addresses and ports',
      'It converts IPv4 to IPv6',
      'It resolves domain names to IP addresses',
    ],
    answer: [1],
    explain:
      'Network Address Translation rewrites private source addresses (192.168.x.x, 10.x.x.x) to the router\'s single public IP, tracking a port mapping so replies get routed back to the right device. It is the main reason IPv4 has survived address exhaustion — and the reason peer-to-peer connections need hole-punching or a relay.',
    hint: 'Your home has one public IP but a dozen connected devices. Something has to reconcile that.',
    tags: ['ip'],
  },
  {
    id: 'net-7',
    world: 'networking',
    skill: 'net.ip',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'How many usable host addresses does the subnet 192.168.1.0/26 provide?',
    choices: ['64', '62', '32', '30'],
    answer: [1],
    explain:
      'A /26 leaves 32 − 26 = 6 host bits, so 2⁶ = 64 total addresses. Subtract two — the network address (all host bits 0) and the broadcast address (all host bits 1) — leaving **62** usable. The formula 2^(32−prefix) − 2 is worth memorising; subnetting questions appear constantly in service-company written rounds.',
    hint: 'Count the host bits, raise 2 to that power, then remember two addresses are always reserved.',
    followUp: 'How many /26 subnets fit inside a /24?',
    tags: ['subnetting', 'classic'],
  },
  {
    id: 'net-8',
    world: 'networking',
    skill: 'net.security',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'In HTTPS, why is asymmetric encryption used only at the start and symmetric encryption thereafter?',
    choices: [
      'Asymmetric encryption is insecure for large payloads',
      'Asymmetric is far slower, so it is used only to safely exchange a symmetric session key',
      'Symmetric encryption cannot be intercepted',
      'Browsers do not support asymmetric encryption for body content',
    ],
    answer: [1],
    explain:
      'Public-key cryptography is orders of magnitude slower than symmetric ciphers like AES. TLS uses it exactly once — to authenticate the server and establish a shared session key without ever transmitting that key in the clear — then switches to fast symmetric encryption for the actual data. Best of both: safe key exchange plus fast bulk transfer.',
    hint: 'Both are secure. The deciding factor here is cost per byte.',
    followUp: 'What does the certificate authority actually guarantee in this handshake?',
    tags: ['tls', 'security'],
  },
  {
    id: 'net-9',
    world: 'networking',
    skill: 'net.model',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'Which protocol maps an IP address to a MAC address on a local network?',
    choices: ['DNS', 'DHCP', 'ARP', 'ICMP'],
    answer: [2],
    explain:
      'ARP (Address Resolution Protocol) broadcasts "who has this IP?" on the local segment and caches the MAC address in the reply. Compare: DNS maps names to IPs, DHCP hands out IPs, and ICMP carries control messages like ping and unreachable errors.',
    hint: 'It bridges Layer 3 addressing down to Layer 2 addressing.',
    tags: ['arp'],
  },
  {
    id: 'net-10',
    world: 'networking',
    skill: 'net.http',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'What makes an HTTP method *idempotent*?',
    choices: [
      'It never modifies server state',
      'Calling it multiple times has the same effect as calling it once',
      'It always returns the same response body',
      'It is cacheable',
    ],
    answer: [1],
    explain:
      'Idempotent means repeated identical requests leave the resource in the same state — GET, PUT and DELETE qualify; POST does not. This matters enormously in practice: a client can safely retry an idempotent request after a network timeout, which is why payment APIs give POST an explicit idempotency key. Note "safe" (no state change at all — GET, HEAD) is a stricter property than idempotent.',
    hint: 'DELETE twice leaves the resource just as gone as deleting once. What property is that?',
    followUp: 'Is PUT idempotent if the body contains "increment the counter"? Why does that break the guarantee?',
    tags: ['http', 'rest'],
  },
]

export const DBMS_QUESTIONS: Question[] = [
  {
    id: 'db-1',
    world: 'dbms',
    skill: 'db.txn',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What does the "D" in ACID guarantee?',
    choices: [
      'Data is distributed across nodes',
      'Once a transaction commits, its changes survive a crash',
      'Duplicate rows are rejected',
      'Deadlocks are impossible',
    ],
    answer: [1],
    explain:
      'Durability: after COMMIT returns, the change is permanent even if the server loses power a millisecond later. This is achieved with a write-ahead log — changes are flushed to the log on durable storage before commit is acknowledged, so recovery can replay them. The others: Atomicity (all or nothing), Consistency (constraints hold), Isolation (concurrent transactions do not interfere).',
    hint: 'Think about what must still be true after someone pulls the power cable.',
    tags: ['acid', 'classic'],
  },
  {
    id: 'db-2',
    world: 'dbms',
    skill: 'db.txn',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Which anomaly does READ COMMITTED prevent but REPEATABLE READ additionally prevents more of?',
    choices: [
      'READ COMMITTED prevents dirty reads; REPEATABLE READ also prevents non-repeatable reads',
      'READ COMMITTED prevents phantom reads; REPEATABLE READ prevents dirty reads',
      'They prevent exactly the same anomalies',
      'REPEATABLE READ prevents nothing extra, only locks longer',
    ],
    answer: [0],
    explain:
      'The ladder: READ UNCOMMITTED allows dirty reads (seeing uncommitted data). READ COMMITTED blocks those but allows non-repeatable reads (same row, different value on re-read). REPEATABLE READ blocks those too but classically allows phantoms (new rows appearing in a re-run range query). SERIALIZABLE blocks all three at the highest concurrency cost.',
    hint: 'Walk the isolation levels in order and note which anomaly each one newly eliminates.',
    followUp: 'What exactly is a phantom read, and which level is needed to eliminate it?',
    tags: ['isolation', 'classic'],
  },
  {
    id: 'db-3',
    world: 'dbms',
    skill: 'db.normal',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'A table is in 1NF. What does moving to 2NF require?',
    choices: [
      'Removing all foreign keys',
      'Eliminating partial dependencies — no non-key attribute depends on only part of a composite primary key',
      'Eliminating transitive dependencies',
      'Ensuring every column holds atomic values',
    ],
    answer: [1],
    explain:
      'The ladder: 1NF = atomic values, no repeating groups. 2NF = 1NF plus no *partial* dependency on a composite key. 3NF = 2NF plus no *transitive* dependency (non-key attribute depending on another non-key attribute). BCNF tightens 3NF so every determinant is a candidate key. Note 2NF is automatically satisfied when the primary key is a single column.',
    hint: 'This level only becomes interesting when the primary key is made of more than one column.',
    followUp: 'When would you deliberately denormalise, and what do you give up?',
    tags: ['normalisation', 'classic'],
  },
  {
    id: 'db-4',
    world: 'dbms',
    skill: 'db.index',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'When does adding an index HURT performance?',
    choices: [
      'Never — indexes only help',
      'On write-heavy tables, since every INSERT/UPDATE/DELETE must also maintain the index',
      'Only on tables with fewer than 10 rows',
      'When the column is a primary key',
    ],
    answer: [1],
    explain:
      'Every index is a second structure the engine must keep in sync on every write, plus extra disk space. Indexes are also useless on low-cardinality columns (a boolean flag) where the planner will just scan anyway. The right framing in an interview: indexes trade write speed and storage for read speed — so index what you filter, join and sort on, and nothing else.',
    hint: 'An index is not free. What does the database have to do every time a row changes?',
    followUp: 'What is a covering index, and why can it skip reading the table entirely?',
    tags: ['indexing'],
  },
  {
    id: 'db-5',
    world: 'dbms',
    skill: 'db.index',
    kind: 'mcq',
    difficulty: 4,
    prompt: 'Why do databases use B+ trees for indexes rather than binary search trees?',
    choices: [
      'B+ trees use less memory per node',
      'High branching factor means far fewer disk reads — depth 3-4 covers millions of rows',
      'Binary search trees cannot store duplicate keys',
      'B+ trees do not need to be balanced',
    ],
    answer: [1],
    explain:
      'Disk I/O dominates. A B+ tree node is sized to one disk page and holds hundreds of keys, so the tree stays 3–4 levels deep even for millions of rows — meaning 3–4 page reads per lookup. A binary tree over the same data would be ~20+ levels, and each level is potentially a separate disk seek. B+ trees also chain their leaves, which makes range scans sequential.',
    hint: 'The bottleneck is not comparisons — it is how many times you have to touch the disk.',
    followUp: 'Why do B+ trees store all actual data in the leaves rather than internal nodes?',
    tags: ['indexing', 'b-tree'],
  },
  {
    id: 'db-6',
    world: 'dbms',
    skill: 'db.model',
    kind: 'mcq',
    difficulty: 2,
    prompt: 'What is the difference between a primary key and a unique key?',
    choices: [
      'They are identical',
      'A primary key cannot be NULL and there is exactly one per table; unique keys allow NULL and you can have many',
      'Unique keys cannot be indexed',
      'A primary key can be NULL but a unique key cannot',
    ],
    answer: [1],
    explain:
      'A primary key is the table\'s single canonical identifier: NOT NULL, unique, one per table, and usually the clustering key. A unique constraint also enforces uniqueness but permits NULLs (in most engines, multiple NULLs — since NULL never equals NULL) and you can declare several per table.',
    hint: 'Consider how many of each a table may have, and how each treats missing values.',
    tags: ['keys'],
  },
  {
    id: 'db-7',
    world: 'dbms',
    skill: 'db.model',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'How is a many-to-many relationship implemented in a relational schema?',
    choices: [
      'A comma-separated list column on one side',
      'A junction (bridge) table holding foreign keys to both entities',
      'A foreign key on both tables pointing at each other',
      'Relational databases cannot express many-to-many',
    ],
    answer: [1],
    explain:
      'Students ↔ Courses becomes three tables: students, courses, and an enrollments table with `student_id` and `course_id` as foreign keys (often together forming the composite primary key). The junction table is also the natural place for relationship attributes like enrollment date or grade — which is a strong follow-up answer.',
    hint: 'Neither table can hold a variable number of references to the other. So where does the relationship live?',
    tags: ['modelling', 'classic'],
  },
  {
    id: 'db-8',
    world: 'dbms',
    skill: 'db.txn',
    kind: 'mcq',
    difficulty: 3,
    prompt: 'Two transactions each hold a lock the other needs. What does the DBMS typically do?',
    choices: [
      'Wait indefinitely for one to give up',
      'Detect the cycle and abort one transaction as the deadlock victim',
      'Merge the two transactions',
      'Escalate both to SERIALIZABLE',
    ],
    answer: [1],
    explain:
      'Databases maintain a wait-for graph and periodically look for cycles. On detection they roll back the "cheapest" transaction — usually the one with least work done — and return a deadlock error, expecting the application to retry. Prevention advice worth stating: always acquire locks in a consistent order across your codebase.',
    hint: 'The database cannot let both wait forever, so something has to give.',
    followUp: 'What application-level pattern most reliably prevents deadlocks in the first place?',
    tags: ['deadlock', 'transactions'],
  },
]
